// Compiles a dart2wasm-generated main module from `source` which can then
// instantiatable via the `instantiate` method.
//
// `source` needs to be a `Response` object (or promise thereof) e.g. created
// via the `fetch()` JS API.
export async function compileStreaming(source) {
  const builtins = {builtins: ['js-string']};
  return new CompiledApp(
      await WebAssembly.compileStreaming(source, builtins), builtins);
}

// Compiles a dart2wasm-generated wasm modules from `bytes` which is then
// instantiatable via the `instantiate` method.
export async function compile(bytes) {
  const builtins = {builtins: ['js-string']};
  return new CompiledApp(await WebAssembly.compile(bytes, builtins), builtins);
}

// DEPRECATED: Please use `compile` or `compileStreaming` to get a compiled app,
// use `instantiate` method to get an instantiated app and then call
// `invokeMain` to invoke the main function.
export async function instantiate(modulePromise, importObjectPromise) {
  var moduleOrCompiledApp = await modulePromise;
  if (!(moduleOrCompiledApp instanceof CompiledApp)) {
    moduleOrCompiledApp = new CompiledApp(moduleOrCompiledApp);
  }
  const instantiatedApp = await moduleOrCompiledApp.instantiate(await importObjectPromise);
  return instantiatedApp.instantiatedModule;
}

// DEPRECATED: Please use `compile` or `compileStreaming` to get a compiled app,
// use `instantiate` method to get an instantiated app and then call
// `invokeMain` to invoke the main function.
export const invoke = (moduleInstance, ...args) => {
  moduleInstance.exports.$invokeMain(args);
}

class CompiledApp {
  constructor(module, builtins) {
    this.module = module;
    this.builtins = builtins;
  }

  // The second argument is an options object containing:
  // `loadDeferredModule` is a JS function that takes a module name matching a
  //   wasm file produced by the dart2wasm compiler and returns the bytes to
  //   load the module. These bytes can be in either a format supported by
  //   `WebAssembly.compile` or `WebAssembly.compileStreaming`.
  // `loadDynamicModule` is a JS function that takes two string names matching,
  //   in order, a wasm file produced by the dart2wasm compiler during dynamic
  //   module compilation and a corresponding js file produced by the same
  //   compilation. It should return a JS Array containing 2 elements. The first
  //   should be the bytes for the wasm module in a format supported by
  //   `WebAssembly.compile` or `WebAssembly.compileStreaming`. The second
  //   should be the result of using the JS 'import' API on the js file path.
  // `loadDeferredId` is a JS function that takes a string corresponding to a load
  //   ID generated by the compiler when 'load-ids' option is passed. Each load
  //   ID maps to one or more WASM modules produced by the compiler. This
  //   function should return an array of byte arrays corresponding to all the
  //   modules specified by that load ID. The arrays should be in a format
  //   supported by `WebAssembly.compile` or `WebAssembly.compileStreaming`.
  async instantiate(additionalImports,
      {loadDeferredModule, loadDynamicModule, loadDeferredId} = {}) {
    let dartInstance;

    // Prints to the console
    function printToConsole(value) {
      if (typeof dartPrint == "function") {
        dartPrint(value);
        return;
      }
      if (typeof console == "object" && typeof console.log != "undefined") {
        console.log(value);
        return;
      }
      if (typeof print == "function") {
        print(value);
        return;
      }

      throw "Unable to print message: " + value;
    }

    // A special symbol attached to functions that wrap Dart functions.
    const jsWrappedDartFunctionSymbol = Symbol("JSWrappedDartFunction");

    function finalizeWrapper(dartFunction, wrapped) {
      wrapped.dartFunction = dartFunction;
      wrapped[jsWrappedDartFunctionSymbol] = true;
      return wrapped;
    }

    // Imports
    const dart2wasm = {
            _1: (decoder, codeUnits) => decoder.decode(codeUnits),
      _2: () => new TextDecoder("utf-8", {fatal: true}),
      _3: () => new TextDecoder("utf-8", {fatal: false}),
      _4: (s) => +s,
      _5: x0 => new Uint8Array(x0),
      _6: (x0,x1,x2) => x0.set(x1,x2),
      _7: (x0,x1) => x0.transferFromImageBitmap(x1),
      _9: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._9(f,arguments.length,x0) }),
      _10: x0 => new window.FinalizationRegistry(x0),
      _11: (x0,x1,x2,x3) => x0.register(x1,x2,x3),
      _12: (x0,x1) => x0.unregister(x1),
      _13: (x0,x1,x2) => x0.slice(x1,x2),
      _14: (x0,x1) => x0.decode(x1),
      _15: (x0,x1) => x0.segment(x1),
      _16: () => new TextDecoder(),
      _18: x0 => x0.buffer,
      _19: x0 => x0.wasmMemory,
      _20: () => globalThis.window._flutter_skwasmInstance,
      _21: x0 => x0.rasterStartMilliseconds,
      _22: x0 => x0.rasterEndMilliseconds,
      _23: x0 => x0.imageBitmaps,
      _139: (x0,x1) => x0.appendChild(x1),
      _170: (x0,x1,x2) => x0.addEventListener(x1,x2),
      _171: (x0,x1,x2) => x0.removeEventListener(x1,x2),
      _172: (x0,x1) => new OffscreenCanvas(x0,x1),
      _173: x0 => x0.remove(),
      _174: (x0,x1) => x0.append(x1),
      _176: x0 => x0.unlock(),
      _177: x0 => x0.getReader(),
      _178: (x0,x1) => x0.item(x1),
      _179: x0 => x0.next(),
      _180: x0 => x0.now(),
      _181: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._181(f,arguments.length,x0) }),
      _182: (x0,x1) => x0.addListener(x1),
      _183: (x0,x1) => x0.removeListener(x1),
      _184: (x0,x1) => x0.matchMedia(x1),
      _185: (x0,x1) => x0.revokeObjectURL(x1),
      _186: x0 => x0.close(),
      _187: (x0,x1,x2,x3,x4) => ({type: x0,data: x1,premultiplyAlpha: x2,colorSpaceConversion: x3,preferAnimation: x4}),
      _188: x0 => new window.ImageDecoder(x0),
      _189: (x0,x1) => ({frameIndex: x0,completeFramesOnly: x1}),
      _190: (x0,x1) => x0.decode(x1),
      _191: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._191(f,arguments.length,x0) }),
      _192: (x0,x1,x2,x3) => x0.addEventListener(x1,x2,x3),
      _194: (x0,x1) => x0.getModifierState(x1),
      _195: x0 => x0.preventDefault(),
      _196: x0 => x0.stopPropagation(),
      _197: (x0,x1) => x0.removeProperty(x1),
      _198: (x0,x1) => x0.prepend(x1),
      _199: x0 => new Intl.Locale(x0),
      _200: (x0,x1) => x0.observe(x1),
      _201: x0 => x0.disconnect(),
      _202: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._202(f,arguments.length,x0) }),
      _203: (x0,x1) => x0.getAttribute(x1),
      _204: (x0,x1) => x0.contains(x1),
      _205: (x0,x1) => x0.querySelector(x1),
      _206: x0 => x0.blur(),
      _207: x0 => x0.hasFocus(),
      _208: (x0,x1) => x0.removeAttribute(x1),
      _209: (x0,x1,x2) => x0.insertBefore(x1,x2),
      _210: (x0,x1) => x0.hasAttribute(x1),
      _211: (x0,x1) => x0.getModifierState(x1),
      _212: (x0,x1) => x0.createTextNode(x1),
      _213: x0 => x0.getBoundingClientRect(),
      _214: (x0,x1) => x0.closest(x1),
      _215: () => new Array(),
      _651: x0 => new Uint8Array(x0),
      _655: () => globalThis.window.flutterConfiguration,
      _657: x0 => x0.assetBase,
      _662: x0 => x0.canvasKitMaximumSurfaces,
      _663: x0 => x0.debugShowSemanticsNodes,
      _664: x0 => x0.hostElement,
      _665: x0 => x0.multiViewEnabled,
      _666: x0 => x0.nonce,
      _668: x0 => x0.fontFallbackBaseUrl,
      _678: x0 => x0.console,
      _679: x0 => x0.devicePixelRatio,
      _680: x0 => x0.document,
      _681: x0 => x0.history,
      _682: x0 => x0.innerHeight,
      _683: x0 => x0.innerWidth,
      _684: x0 => x0.location,
      _685: x0 => x0.navigator,
      _686: x0 => x0.visualViewport,
      _687: x0 => x0.performance,
      _689: x0 => x0.URL,
      _691: (x0,x1) => x0.getComputedStyle(x1),
      _692: x0 => x0.screen,
      _693: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._693(f,arguments.length,x0) }),
      _694: (x0,x1) => x0.requestAnimationFrame(x1),
      _698: (x0,x1) => x0.warn(x1),
      _700: (x0,x1) => x0.debug(x1),
      _701: x0 => globalThis.parseFloat(x0),
      _702: () => globalThis.window,
      _703: () => globalThis.Intl,
      _704: () => globalThis.Symbol,
      _705: (x0,x1,x2,x3,x4) => globalThis.createImageBitmap(x0,x1,x2,x3,x4),
      _707: x0 => x0.clipboard,
      _708: x0 => x0.maxTouchPoints,
      _709: x0 => x0.vendor,
      _710: x0 => x0.language,
      _711: x0 => x0.platform,
      _712: x0 => x0.userAgent,
      _713: (x0,x1) => x0.vibrate(x1),
      _714: x0 => x0.languages,
      _715: x0 => x0.documentElement,
      _716: (x0,x1) => x0.querySelector(x1),
      _717: (x0,x1) => x0.querySelectorAll(x1),
      _719: (x0,x1) => x0.createElement(x1),
      _722: (x0,x1) => x0.createEvent(x1),
      _723: x0 => x0.activeElement,
      _726: x0 => x0.head,
      _727: x0 => x0.body,
      _728: (x0,x1) => { x0.title = x1 },
      _732: x0 => x0.visibilityState,
      _733: () => globalThis.document,
      _734: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._734(f,arguments.length,x0) }),
      _735: (x0,x1) => x0.dispatchEvent(x1),
      _743: x0 => x0.target,
      _745: x0 => x0.timeStamp,
      _746: x0 => x0.type,
      _748: (x0,x1,x2,x3) => x0.initEvent(x1,x2,x3),
      _755: x0 => x0.firstChild,
      _759: x0 => x0.parentElement,
      _761: (x0,x1) => { x0.textContent = x1 },
      _762: x0 => x0.parentNode,
      _763: x0 => x0.nextSibling,
      _764: (x0,x1) => x0.removeChild(x1),
      _765: x0 => x0.isConnected,
      _773: x0 => x0.clientHeight,
      _774: x0 => x0.clientWidth,
      _775: x0 => x0.offsetHeight,
      _776: x0 => x0.offsetWidth,
      _777: x0 => x0.id,
      _778: (x0,x1) => { x0.id = x1 },
      _781: (x0,x1) => { x0.spellcheck = x1 },
      _782: x0 => x0.tagName,
      _783: x0 => x0.style,
      _786: (x0,x1) => x0.querySelectorAll(x1),
      _787: (x0,x1,x2) => x0.setAttribute(x1,x2),
      _788: (x0,x1) => { x0.tabIndex = x1 },
      _789: x0 => x0.tabIndex,
      _790: (x0,x1) => x0.focus(x1),
      _791: x0 => x0.scrollTop,
      _792: (x0,x1) => { x0.scrollTop = x1 },
      _793: x0 => x0.scrollLeft,
      _794: (x0,x1) => { x0.scrollLeft = x1 },
      _795: x0 => x0.classList,
      _797: (x0,x1) => { x0.className = x1 },
      _799: (x0,x1) => x0.getElementsByClassName(x1),
      _800: x0 => x0.click(),
      _801: (x0,x1) => x0.attachShadow(x1),
      _804: x0 => x0.computedStyleMap(),
      _805: (x0,x1) => x0.get(x1),
      _811: (x0,x1) => x0.getPropertyValue(x1),
      _812: (x0,x1,x2,x3) => x0.setProperty(x1,x2,x3),
      _813: x0 => x0.offsetLeft,
      _814: x0 => x0.offsetTop,
      _815: x0 => x0.offsetParent,
      _817: (x0,x1) => { x0.name = x1 },
      _818: x0 => x0.content,
      _819: (x0,x1) => { x0.content = x1 },
      _823: (x0,x1) => { x0.src = x1 },
      _824: x0 => x0.naturalWidth,
      _825: x0 => x0.naturalHeight,
      _829: (x0,x1) => { x0.crossOrigin = x1 },
      _831: (x0,x1) => { x0.decoding = x1 },
      _832: x0 => x0.decode(),
      _837: (x0,x1) => { x0.nonce = x1 },
      _841: (x0,x1) => { x0.width = x1 },
      _844: (x0,x1) => { x0.height = x1 },
      _847: (x0,x1) => x0.getContext(x1),
      _914: x0 => x0.width,
      _915: x0 => x0.height,
      _917: (x0,x1) => x0.fetch(x1),
      _918: x0 => x0.status,
      _920: x0 => x0.body,
      _921: x0 => x0.arrayBuffer(),
      _924: x0 => x0.read(),
      _925: x0 => x0.value,
      _926: x0 => x0.done,
      _933: x0 => x0.name,
      _934: x0 => x0.x,
      _935: x0 => x0.y,
      _938: x0 => x0.top,
      _939: x0 => x0.right,
      _940: x0 => x0.bottom,
      _941: x0 => x0.left,
      _951: x0 => x0.height,
      _952: x0 => x0.width,
      _953: x0 => x0.scale,
      _954: (x0,x1) => { x0.value = x1 },
      _957: (x0,x1) => { x0.placeholder = x1 },
      _959: (x0,x1) => { x0.name = x1 },
      _960: x0 => x0.selectionDirection,
      _961: x0 => x0.selectionStart,
      _962: x0 => x0.selectionEnd,
      _965: x0 => x0.value,
      _967: (x0,x1,x2) => x0.setSelectionRange(x1,x2),
      _968: x0 => x0.readText(),
      _969: (x0,x1) => x0.writeText(x1),
      _971: x0 => x0.altKey,
      _972: x0 => x0.code,
      _973: x0 => x0.ctrlKey,
      _974: x0 => x0.key,
      _975: x0 => x0.keyCode,
      _976: x0 => x0.location,
      _977: x0 => x0.metaKey,
      _978: x0 => x0.repeat,
      _979: x0 => x0.shiftKey,
      _980: x0 => x0.isComposing,
      _982: x0 => x0.state,
      _983: (x0,x1) => x0.go(x1),
      _985: (x0,x1,x2,x3) => x0.pushState(x1,x2,x3),
      _986: (x0,x1,x2,x3) => x0.replaceState(x1,x2,x3),
      _987: x0 => x0.pathname,
      _988: x0 => x0.search,
      _989: x0 => x0.hash,
      _993: x0 => x0.state,
      _996: (x0,x1) => x0.createObjectURL(x1),
      _998: x0 => new Blob(x0),
      _1008: x0 => x0.matches,
      _1009: x0 => x0.matches,
      _1013: x0 => x0.relatedTarget,
      _1015: x0 => x0.clientX,
      _1016: x0 => x0.clientY,
      _1017: x0 => x0.offsetX,
      _1018: x0 => x0.offsetY,
      _1021: x0 => x0.button,
      _1022: x0 => x0.buttons,
      _1023: x0 => x0.ctrlKey,
      _1027: x0 => x0.pointerId,
      _1028: x0 => x0.pointerType,
      _1029: x0 => x0.pressure,
      _1030: x0 => x0.tiltX,
      _1031: x0 => x0.tiltY,
      _1032: x0 => x0.getCoalescedEvents(),
      _1035: x0 => x0.deltaX,
      _1036: x0 => x0.deltaY,
      _1037: x0 => x0.wheelDeltaX,
      _1038: x0 => x0.wheelDeltaY,
      _1039: x0 => x0.deltaMode,
      _1046: x0 => x0.changedTouches,
      _1049: x0 => x0.clientX,
      _1050: x0 => x0.clientY,
      _1053: x0 => x0.data,
      _1056: (x0,x1) => { x0.disabled = x1 },
      _1058: (x0,x1) => { x0.type = x1 },
      _1059: (x0,x1) => { x0.max = x1 },
      _1060: (x0,x1) => { x0.min = x1 },
      _1061: (x0,x1) => { x0.value = x1 },
      _1062: x0 => x0.value,
      _1063: x0 => x0.disabled,
      _1064: (x0,x1) => { x0.disabled = x1 },
      _1066: (x0,x1) => { x0.placeholder = x1 },
      _1068: (x0,x1) => { x0.name = x1 },
      _1069: (x0,x1) => { x0.autocomplete = x1 },
      _1071: x0 => x0.selectionDirection,
      _1072: x0 => x0.selectionStart,
      _1074: x0 => x0.selectionEnd,
      _1077: (x0,x1,x2) => x0.setSelectionRange(x1,x2),
      _1078: (x0,x1) => x0.add(x1),
      _1081: (x0,x1) => { x0.noValidate = x1 },
      _1082: (x0,x1) => { x0.method = x1 },
      _1083: (x0,x1) => { x0.action = x1 },
      _1108: x0 => x0.orientation,
      _1109: x0 => x0.width,
      _1110: x0 => x0.height,
      _1111: (x0,x1) => x0.lock(x1),
      _1130: x0 => new ResizeObserver(x0),
      _1133: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1133(f,arguments.length,x0,x1) }),
      _1141: x0 => x0.length,
      _1142: x0 => x0.iterator,
      _1143: x0 => x0.Segmenter,
      _1144: x0 => x0.v8BreakIterator,
      _1145: (x0,x1) => new Intl.Segmenter(x0,x1),
      _1148: x0 => x0.language,
      _1149: x0 => x0.script,
      _1150: x0 => x0.region,
      _1168: x0 => x0.done,
      _1169: x0 => x0.value,
      _1170: x0 => x0.index,
      _1174: (x0,x1) => new Intl.v8BreakIterator(x0,x1),
      _1175: (x0,x1) => x0.adoptText(x1),
      _1176: x0 => x0.first(),
      _1177: x0 => x0.next(),
      _1178: x0 => x0.current(),
      _1191: x0 => x0.hostElement,
      _1192: x0 => x0.viewConstraints,
      _1195: x0 => x0.maxHeight,
      _1196: x0 => x0.maxWidth,
      _1197: x0 => x0.minHeight,
      _1198: x0 => x0.minWidth,
      _1199: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1199(f,arguments.length,x0) }),
      _1200: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1200(f,arguments.length,x0) }),
      _1201: (x0,x1) => ({addView: x0,removeView: x1}),
      _1204: x0 => x0.loader,
      _1205: () => globalThis._flutter,
      _1206: (x0,x1) => x0.didCreateEngineInitializer(x1),
      _1207: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1207(f,arguments.length,x0) }),
      _1208: (module,f) => finalizeWrapper(f, function() { return module.exports._1208(f,arguments.length) }),
      _1209: (x0,x1) => ({initializeEngine: x0,autoStart: x1}),
      _1212: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1212(f,arguments.length,x0) }),
      _1213: x0 => ({runApp: x0}),
      _1215: (x0,x1,x2) => x0.call(x1,x2),
      _1216: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1216(f,arguments.length,x0,x1) }),
      _1217: x0 => new Promise(x0),
      _1218: x0 => x0.length,
      _1219: () => globalThis.window.ImageDecoder,
      _1220: x0 => x0.tracks,
      _1222: x0 => x0.completed,
      _1224: x0 => x0.image,
      _1230: x0 => x0.displayWidth,
      _1231: x0 => x0.displayHeight,
      _1232: x0 => x0.duration,
      _1235: x0 => x0.ready,
      _1236: x0 => x0.selectedTrack,
      _1237: x0 => x0.repetitionCount,
      _1238: x0 => x0.frameCount,
      _1281: (x0,x1) => x0.getElementById(x1),
      _1295: x0 => globalThis.URL.createObjectURL(x0),
      _1297: x0 => globalThis.URL.revokeObjectURL(x0),
      _1307: x0 => new Float32Array(x0),
      _1309: x0 => x0.close(),
      _1310: (x0,x1) => x0.send(x1),
      _1311: x0 => new WebSocket(x0),
      _1312: () => new MediaStream(),
      _1313: x0 => x0.getVideoTracks(),
      _1314: (x0,x1) => x0.addTrack(x1),
      _1315: x0 => x0.getAudioTracks(),
      _1316: (x0,x1) => x0.append(x1),
      _1319: x0 => x0.remove(),
      _1321: (x0,x1,x2) => x0.setAttribute(x1,x2),
      _1322: (x0,x1) => x0.appendChild(x1),
      _1323: x0 => x0.play(),
      _1338: (x0,x1) => x0.createElement(x1),
      _1344: (x0,x1,x2) => x0.addEventListener(x1,x2),
      _1345: (x0,x1) => x0.get(x1),
      _1346: x0 => x0.text(),
      _1350: x0 => x0.call(),
      _1351: (x0,x1,x2,x3,x4) => x0.call(x1,x2,x3,x4),
      _1355: (x0,x1,x2) => x0.call(x1,x2),
      _1356: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1356(f,arguments.length,x0,x1) }),
      _1357: x0 => new ResizeObserver(x0),
      _1358: (x0,x1) => x0.observe(x1),
      _1359: (x0,x1,x2,x3) => x0.call(x1,x2,x3),
      _1360: x0 => x0.arrayBuffer(),
      _1363: (x0,x1) => x0.call(x1),
      _1364: (x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13,x14,x15,x16,x17,x18,x19,x20) => x0.call(x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13,x14,x15,x16,x17,x18,x19,x20),
      _1365: x0 => x0.call(),
      _1366: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1366(f,arguments.length,x0) }),
      _1367: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1367(f,arguments.length,x0) }),
      _1368: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3) { return module.exports._1368(f,arguments.length,x0,x1,x2,x3) }),
      _1369: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1369(f,arguments.length,x0) }),
      _1370: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._1370(f,arguments.length,x0,x1,x2) }),
      _1371: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3) { return module.exports._1371(f,arguments.length,x0,x1,x2,x3) }),
      _1372: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3,x4,x5,x6,x7,x8) { return module.exports._1372(f,arguments.length,x0,x1,x2,x3,x4,x5,x6,x7,x8) }),
      _1373: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3,x4) { return module.exports._1373(f,arguments.length,x0,x1,x2,x3,x4) }),
      _1374: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1374(f,arguments.length,x0,x1) }),
      _1375: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1375(f,arguments.length,x0) }),
      _1376: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1376(f,arguments.length,x0) }),
      _1377: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3,x4,x5,x6) { return module.exports._1377(f,arguments.length,x0,x1,x2,x3,x4,x5,x6) }),
      _1378: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._1378(f,arguments.length,x0,x1,x2) }),
      _1379: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._1379(f,arguments.length,x0,x1,x2) }),
      _1380: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._1380(f,arguments.length,x0,x1,x2) }),
      _1381: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1381(f,arguments.length,x0) }),
      _1382: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1382(f,arguments.length,x0) }),
      _1383: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1383(f,arguments.length,x0) }),
      _1384: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1384(f,arguments.length,x0) }),
      _1385: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1385(f,arguments.length,x0) }),
      _1386: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1386(f,arguments.length,x0,x1) }),
      _1387: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1387(f,arguments.length,x0,x1) }),
      _1388: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1388(f,arguments.length,x0,x1) }),
      _1389: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1389(f,arguments.length,x0,x1) }),
      _1390: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1390(f,arguments.length,x0,x1) }),
      _1391: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1391(f,arguments.length,x0,x1) }),
      _1392: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1392(f,arguments.length,x0,x1) }),
      _1393: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1393(f,arguments.length,x0,x1) }),
      _1394: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1394(f,arguments.length,x0,x1) }),
      _1395: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1395(f,arguments.length,x0) }),
      _1396: (x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11) => x0.call(x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11),
      _1397: (x0,x1,x2,x3,x4) => x0.call(x1,x2,x3,x4),
      _1399: (x0,x1,x2,x3,x4,x5) => x0.call(x1,x2,x3,x4,x5),
      _1400: (x0,x1,x2,x3,x4,x5,x6,x7,x8) => x0.call(x1,x2,x3,x4,x5,x6,x7,x8),
      _1409: (x0,x1,x2,x3,x4,x5,x6) => x0.call(x1,x2,x3,x4,x5,x6),
      _1425: (x0,x1,x2,x3) => x0.addEventListener(x1,x2,x3),
      _1426: (x0,x1,x2,x3) => x0.removeEventListener(x1,x2,x3),
      _1427: (x0,x1) => x0.createElement(x1),
      _1432: (x0,x1,x2,x3) => x0.open(x1,x2,x3),
      _1442: x0 => x0.click(),
      _1445: () => globalThis.Notification.requestPermission(),
      _1446: (x0,x1,x2,x3) => x0.drawImage(x1,x2,x3),
      _1448: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1448(f,arguments.length,x0) }),
      _1449: (x0,x1,x2,x3) => x0.toBlob(x1,x2,x3),
      _1450: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1450(f,arguments.length,x0) }),
      _1451: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1451(f,arguments.length,x0) }),
      _1452: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1452(f,arguments.length,x0) }),
      _1453: (x0,x1) => x0.querySelector(x1),
      _1454: (x0,x1) => x0.replaceChildren(x1),
      _1463: x0 => x0.decode(),
      _1464: (x0,x1,x2,x3) => x0.open(x1,x2,x3),
      _1465: (x0,x1,x2) => x0.setRequestHeader(x1,x2),
      _1466: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1466(f,arguments.length,x0) }),
      _1467: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1467(f,arguments.length,x0) }),
      _1468: x0 => x0.send(),
      _1469: () => new XMLHttpRequest(),
      _1470: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1470(f,arguments.length,x0) }),
      _1471: (x0,x1) => x0.getItem(x1),
      _1472: (x0,x1) => x0.removeItem(x1),
      _1473: (x0,x1,x2) => x0.setItem(x1,x2),
      _1477: (x0,x1) => x0.getUserMedia(x1),
      _1478: x0 => x0.stop(),
      _1485: x0 => x0.deviceMemory,
      _1487: (x0,x1,x2,x3,x4,x5,x6,x7) => ({apiKey: x0,authDomain: x1,databaseURL: x2,projectId: x3,storageBucket: x4,messagingSenderId: x5,measurementId: x6,appId: x7}),
      _1488: (x0,x1) => globalThis.firebase_core.initializeApp(x0,x1),
      _1489: x0 => globalThis.firebase_core.getApp(x0),
      _1490: () => globalThis.firebase_core.getApp(),
      _1491: (x0,x1,x2) => globalThis.firebase_core.registerVersion(x0,x1,x2),
      _1493: x0 => globalThis.firebase_messaging.getMessaging(x0),
      _1495: (x0,x1) => globalThis.firebase_messaging.getToken(x0,x1),
      _1497: (x0,x1) => globalThis.firebase_messaging.onMessage(x0,x1),
      _1498: (x0,x1) => ({next: x0,error: x1}),
      _1501: x0 => ({vapidKey: x0}),
      _1503: x0 => x0.title,
      _1504: x0 => x0.body,
      _1505: x0 => x0.image,
      _1506: x0 => x0.messageId,
      _1507: x0 => x0.collapseKey,
      _1508: x0 => x0.fcmOptions,
      _1509: x0 => x0.notification,
      _1510: x0 => x0.data,
      _1511: x0 => x0.from,
      _1512: x0 => x0.analyticsLabel,
      _1513: x0 => x0.link,
      _1514: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1514(f,arguments.length,x0) }),
      _1515: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1515(f,arguments.length,x0) }),
      _1517: () => globalThis.firebase_core.SDK_VERSION,
      _1523: x0 => x0.apiKey,
      _1525: x0 => x0.authDomain,
      _1527: x0 => x0.databaseURL,
      _1529: x0 => x0.projectId,
      _1531: x0 => x0.storageBucket,
      _1533: x0 => x0.messagingSenderId,
      _1535: x0 => x0.measurementId,
      _1537: x0 => x0.appId,
      _1539: x0 => x0.name,
      _1540: x0 => x0.options,
      _1541: (x0,x1) => x0.debug(x1),
      _1542: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1542(f,arguments.length,x0) }),
      _1543: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1543(f,arguments.length,x0,x1) }),
      _1544: (x0,x1) => ({createScript: x0,createScriptURL: x1}),
      _1545: (x0,x1,x2) => x0.createPolicy(x1,x2),
      _1546: (x0,x1) => x0.createScriptURL(x1),
      _1547: (x0,x1,x2) => x0.createScript(x1,x2),
      _1548: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1548(f,arguments.length,x0) }),
      _1549: () => new SpeechSynthesisUtterance(),
      _1550: x0 => x0.pause(),
      _1551: x0 => x0.resume(),
      _1552: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1552(f,arguments.length,x0) }),
      _1553: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1553(f,arguments.length,x0) }),
      _1554: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1554(f,arguments.length,x0) }),
      _1555: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1555(f,arguments.length,x0) }),
      _1556: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1556(f,arguments.length,x0) }),
      _1557: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1557(f,arguments.length,x0) }),
      _1558: (x0,x1) => x0.speak(x1),
      _1559: x0 => x0.cancel(),
      _1560: x0 => x0.getVoices(),
      _1565: Date.now,
      _1567: s => new Date(s * 1000).getTimezoneOffset() * 60,
      _1568: s => {
        if (!/^\s*[+-]?(?:Infinity|NaN|(?:\.\d+|\d+(?:\.\d*)?)(?:[eE][+-]?\d+)?)\s*$/.test(s)) {
          return NaN;
        }
        return parseFloat(s);
      },
      _1569: () => new Error().stack,
      _1570: () => typeof dartUseDateNowForTicks !== "undefined",
      _1571: () => 1000 * performance.now(),
      _1572: () => Date.now(),
      _1573: () => {
        // On browsers return `globalThis.location.href`
        if (globalThis.location != null) {
          return globalThis.location.href;
        }
        return null;
      },
      _1574: () => {
        return typeof process != "undefined" &&
               Object.prototype.toString.call(process) == "[object process]" &&
               process.platform == "win32"
      },
      _1575: () => new WeakMap(),
      _1576: (map, o) => map.get(o),
      _1577: (map, o, v) => map.set(o, v),
      _1578: (exn) => exn.toString(),
      _1579: (exn) => exn.stack,
      _1580: (exn) => {
        let stackString = exn.toString();
        let frames = stackString.split('\n');
        let drop = 2;
        if (frames[0] === 'Error') {
            drop += 1;
        }
        return frames.slice(drop).join('\n');
      },
      _1581: x0 => new WeakRef(x0),
      _1582: x0 => x0.deref(),
      _1583: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1583(f,arguments.length,x0) }),
      _1584: x0 => new FinalizationRegistry(x0),
      _1585: (x0,x1,x2,x3) => x0.register(x1,x2,x3),
      _1587: (x0,x1) => x0.unregister(x1),
      _1589: () => globalThis.WeakRef,
      _1590: () => globalThis.FinalizationRegistry,
      _1592: s => JSON.stringify(s),
      _1593: s => printToConsole(s),
      _1594: (o, p, r) => o.replaceAll(p, () => r),
      _1595: (o, p, r) => o.replace(p, () => r),
      _1596: Function.prototype.call.bind(String.prototype.toLowerCase),
      _1597: s => s.toUpperCase(),
      _1598: s => s.trim(),
      _1599: s => s.trimLeft(),
      _1600: s => s.trimRight(),
      _1601: (string, times) => string.repeat(times),
      _1602: Function.prototype.call.bind(String.prototype.indexOf),
      _1603: (s, p, i) => s.lastIndexOf(p, i),
      _1604: (string, token) => string.split(token),
      _1605: Object.is,
      _1608: (o, t) => typeof o === t,
      _1609: (o, c) => o instanceof c,
      _1610: o => Object.keys(o),
      _1640: x0 => new Array(x0),
      _1642: x0 => x0.length,
      _1644: (x0,x1) => x0[x1],
      _1645: (x0,x1,x2) => { x0[x1] = x2 },
      _1648: (x0,x1,x2) => new DataView(x0,x1,x2),
      _1650: x0 => new Int8Array(x0),
      _1651: (x0,x1,x2) => new Uint8Array(x0,x1,x2),
      _1653: x0 => new Uint8ClampedArray(x0),
      _1655: x0 => new Int16Array(x0),
      _1657: x0 => new Uint16Array(x0),
      _1659: x0 => new Int32Array(x0),
      _1661: x0 => new Uint32Array(x0),
      _1664: x0 => new Float64Array(x0),
      _1686: x0 => x0.random(),
      _1687: (x0,x1) => x0.getRandomValues(x1),
      _1688: () => globalThis.crypto,
      _1689: () => globalThis.Math,
      _1702: (ms, c) =>
      setTimeout(() => dartInstance.exports.$invokeCallback(c),ms),
      _1703: (handle) => clearTimeout(handle),
      _1704: (ms, c) =>
      setInterval(() => dartInstance.exports.$invokeCallback(c), ms),
      _1705: (handle) => clearInterval(handle),
      _1706: (c) =>
      queueMicrotask(() => dartInstance.exports.$invokeCallback(c)),
      _1707: () => Date.now(),
      _1708: (s, m) => {
        try {
          return new RegExp(s, m);
        } catch (e) {
          return String(e);
        }
      },
      _1709: (x0,x1) => x0.exec(x1),
      _1710: (x0,x1) => x0.test(x1),
      _1711: x0 => x0.pop(),
      _1713: o => o === undefined,
      _1715: o => typeof o === 'function' && o[jsWrappedDartFunctionSymbol] === true,
      _1717: o => {
        const proto = Object.getPrototypeOf(o);
        return proto === Object.prototype || proto === null;
      },
      _1718: o => o instanceof RegExp,
      _1719: (l, r) => l === r,
      _1720: o => o,
      _1721: o => o,
      _1722: o => o,
      _1723: b => !!b,
      _1724: o => o.length,
      _1726: (o, i) => o[i],
      _1727: f => f.dartFunction,
      _1728: () => ({}),
      _1729: () => [],
      _1731: () => globalThis,
      _1732: (constructor, args) => {
        const factoryFunction = constructor.bind.apply(
            constructor, [null, ...args]);
        return new factoryFunction();
      },
      _1734: (o, p) => o[p],
      _1735: (o, p, v) => o[p] = v,
      _1736: (o, m, a) => o[m].apply(o, a),
      _1738: o => String(o),
      _1739: (p, s, f) => p.then(s, (e) => f(e, e === undefined)),
      _1740: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1740(f,arguments.length,x0) }),
      _1741: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1741(f,arguments.length,x0,x1) }),
      _1742: o => {
        if (o === undefined) return 1;
        var type = typeof o;
        if (type === 'boolean') return 2;
        if (type === 'number') return 3;
        if (type === 'string') return 4;
        if (o instanceof Array) return 5;
        if (ArrayBuffer.isView(o)) {
          if (o instanceof Int8Array) return 6;
          if (o instanceof Uint8Array) return 7;
          if (o instanceof Uint8ClampedArray) return 8;
          if (o instanceof Int16Array) return 9;
          if (o instanceof Uint16Array) return 10;
          if (o instanceof Int32Array) return 11;
          if (o instanceof Uint32Array) return 12;
          if (o instanceof Float32Array) return 13;
          if (o instanceof Float64Array) return 14;
          if (o instanceof DataView) return 15;
        }
        if (o instanceof ArrayBuffer) return 16;
        // Feature check for `SharedArrayBuffer` before doing a type-check.
        if (globalThis.SharedArrayBuffer !== undefined &&
            o instanceof SharedArrayBuffer) {
            return 17;
        }
        if (o instanceof Promise) return 18;
        return 19;
      },
      _1743: o => [o],
      _1744: (o0, o1) => [o0, o1],
      _1745: (o0, o1, o2) => [o0, o1, o2],
      _1746: (o0, o1, o2, o3) => [o0, o1, o2, o3],
      _1747: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI8ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1748: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI8ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1749: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI16ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1750: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI16ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1751: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI32ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1752: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI32ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1753: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmF32ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1754: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmF32ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1755: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmF64ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1756: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmF64ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1757: x0 => new ArrayBuffer(x0),
      _1758: s => {
        if (/[[\]{}()*+?.\\^$|]/.test(s)) {
            s = s.replace(/[[\]{}()*+?.\\^$|]/g, '\\$&');
        }
        return s;
      },
      _1759: x0 => x0.input,
      _1760: x0 => x0.index,
      _1762: x0 => x0.flags,
      _1763: x0 => x0.multiline,
      _1764: x0 => x0.ignoreCase,
      _1765: x0 => x0.unicode,
      _1766: x0 => x0.dotAll,
      _1767: (x0,x1) => { x0.lastIndex = x1 },
      _1768: (o, p) => p in o,
      _1769: (o, p) => o[p],
      _1770: (o, p, v) => o[p] = v,
      _1771: (o, p) => delete o[p],
      _1772: (x0,x1) => x0.replaceTrack(x1),
      _1773: x0 => x0.getParameters(),
      _1774: (x0,x1) => x0.setParameters(x1),
      _1775: x0 => x0.getStats(),
      _1776: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1776(f,arguments.length,x0,x1) }),
      _1778: (x0,x1) => x0.setCodecPreferences(x1),
      _1779: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1779(f,arguments.length,x0) }),
      _1780: (x0,x1,x2) => x0.addEventListener(x1,x2),
      _1781: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1781(f,arguments.length,x0) }),
      _1782: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1782(f,arguments.length,x0) }),
      _1783: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1783(f,arguments.length,x0) }),
      _1784: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1784(f,arguments.length,x0) }),
      _1785: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1785(f,arguments.length,x0) }),
      _1786: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1786(f,arguments.length,x0) }),
      _1787: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1787(f,arguments.length,x0) }),
      _1788: x0 => x0.close(),
      _1789: (x0,x1) => x0.setConfiguration(x1),
      _1790: (x0,x1) => x0.createOffer(x1),
      _1791: (x0,x1) => x0.createAnswer(x1),
      _1794: (x0,x1) => ({type: x0,sdp: x1}),
      _1795: (x0,x1) => x0.setLocalDescription(x1),
      _1796: (x0,x1) => ({type: x0,sdp: x1}),
      _1797: (x0,x1) => x0.setRemoteDescription(x1),
      _1798: (x0,x1,x2) => ({candidate: x0,sdpMid: x1,sdpMLineIndex: x2}),
      _1799: (x0,x1) => x0.addIceCandidate(x1),
      _1801: x0 => x0.getStats(),
      _1802: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1802(f,arguments.length,x0,x1) }),
      _1805: (x0,x1,x2,x3) => ({ordered: x0,protocol: x1,negotiated: x2,id: x3}),
      _1806: (x0,x1,x2) => x0.createDataChannel(x1,x2),
      _1807: x0 => x0.restartIce(),
      _1810: (x0,x1) => x0.removeTrack(x1),
      _1811: x0 => x0.getSenders(),
      _1814: (x0,x1,x2) => x0.addTransceiver(x1,x2),
      _1816: (x0,x1) => { x0.binaryType = x1 },
      _1818: x0 => globalThis.RTCRtpReceiver.getCapabilities(x0),
      _1819: x0 => new RTCPeerConnection(x0),
      _1828: x0 => x0.getStats(),
      _1829: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1829(f,arguments.length,x0,x1) }),
      _1831: (x0,x1) => ({video: x0,audio: x1}),
      _1832: (x0,x1) => x0.getDisplayMedia(x1),
      _1833: x0 => x0.enumerateDevices(),
      _1835: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1835(f,arguments.length,x0) }),
      _1843: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1843(f,arguments.length,x0) }),
      _1844: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1844(f,arguments.length,x0) }),
      _1845: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1845(f,arguments.length,x0) }),
      _1848: x0 => x0.getSettings(),
      _1851: (x0,x1) => x0.getContext(x1),
      _1859: () => new XMLHttpRequest(),
      _1860: (x0,x1,x2,x3) => x0.open(x1,x2,x3),
      _1864: x0 => x0.send(),
      _1866: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1866(f,arguments.length,x0) }),
      _1867: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1867(f,arguments.length,x0) }),
      _1873: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1873(f,arguments.length,x0) }),
      _1874: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1874(f,arguments.length,x0) }),
      _1875: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1875(f,arguments.length,x0) }),
      _1876: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1876(f,arguments.length,x0) }),
      _1877: (x0,x1) => x0.send(x1),
      _1879: (x0,x1) => new WebSocket(x0,x1),
      _1880: (x0,x1,x2) => x0.close(x1,x2),
      _1881: (x0,x1) => x0.close(x1),
      _1886: () => new FileReader(),
      _1887: (x0,x1) => x0.readAsArrayBuffer(x1),
      _1888: () => new AbortController(),
      _1889: x0 => x0.abort(),
      _1890: (x0,x1,x2,x3,x4,x5) => ({method: x0,headers: x1,body: x2,credentials: x3,redirect: x4,signal: x5}),
      _1891: (x0,x1) => globalThis.fetch(x0,x1),
      _1892: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._1892(f,arguments.length,x0,x1,x2) }),
      _1893: (x0,x1) => x0.forEach(x1),
      _1894: x0 => x0.getReader(),
      _1895: x0 => x0.cancel(),
      _1896: x0 => x0.read(),
      _1897: x0 => new BroadcastChannel(x0),
      _1898: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1898(f,arguments.length,x0) }),
      _1899: (x0,x1) => x0.postMessage(x1),
      _1900: x0 => x0.close(),
      _1901: (x0,x1,x2,x3) => ({method: x0,headers: x1,body: x2,credentials: x3}),
      _1902: (x0,x1,x2) => x0.fetch(x1,x2),
      _1903: (x0,x1) => x0.key(x1),
      _1904: (x0,x1) => x0.item(x1),
      _2125: x0 => x0.trustedTypes,
      _2126: (x0,x1) => { x0.text = x1 },
      _2127: o => o instanceof Array,
      _2128: (a, i) => a.push(i),
      _2131: (a, l) => a.length = l,
      _2132: a => a.pop(),
      _2133: (a, i) => a.splice(i, 1),
      _2134: (a, s) => a.join(s),
      _2135: (a, s, e) => a.slice(s, e),
      _2137: (a, b) => a == b ? 0 : (a > b ? 1 : -1),
      _2138: a => a.length,
      _2139: (a, l) => a.length = l,
      _2140: (a, i) => a[i],
      _2141: (a, i, v) => a[i] = v,
      _2143: o => {
        if (o instanceof ArrayBuffer) return 0;
        if (globalThis.SharedArrayBuffer !== undefined &&
            o instanceof SharedArrayBuffer) {
          return 1;
        }
        return 2;
      },
      _2144: (o, offsetInBytes, lengthInBytes) => {
        var dst = new ArrayBuffer(lengthInBytes);
        new Uint8Array(dst).set(new Uint8Array(o, offsetInBytes, lengthInBytes));
        return new DataView(dst);
      },
      _2145: o => o instanceof DataView,
      _2146: o => o instanceof Uint8Array,
      _2147: (o, start, length) => new Uint8Array(o.buffer, o.byteOffset + start, length),
      _2148: o => o instanceof Int8Array,
      _2149: (o, start, length) => new Int8Array(o.buffer, o.byteOffset + start, length),
      _2150: o => o instanceof Uint8ClampedArray,
      _2151: (o, start, length) => new Uint8ClampedArray(o.buffer, o.byteOffset + start, length),
      _2152: o => o instanceof Uint16Array,
      _2153: (o, start, length) => new Uint16Array(o.buffer, o.byteOffset + start, length),
      _2154: o => o instanceof Int16Array,
      _2155: (o, start, length) => new Int16Array(o.buffer, o.byteOffset + start, length),
      _2156: o => o instanceof Uint32Array,
      _2157: (o, start, length) => new Uint32Array(o.buffer, o.byteOffset + start, length),
      _2158: o => o instanceof Int32Array,
      _2159: (o, start, length) => new Int32Array(o.buffer, o.byteOffset + start, length),
      _2161: (o, start, length) => new BigInt64Array(o.buffer, o.byteOffset + start, length),
      _2162: o => o instanceof Float32Array,
      _2163: (o, start, length) => new Float32Array(o.buffer, o.byteOffset + start, length),
      _2164: o => o instanceof Float64Array,
      _2165: (o, start, length) => new Float64Array(o.buffer, o.byteOffset + start, length),
      _2166: (t, s) => t.set(s),
      _2167: l => new DataView(new ArrayBuffer(l)),
      _2168: (o) => new DataView(o.buffer, o.byteOffset, o.byteLength),
      _2170: o => o.buffer,
      _2171: o => o.byteOffset,
      _2172: Function.prototype.call.bind(Object.getOwnPropertyDescriptor(DataView.prototype, 'byteLength').get),
      _2173: (b, o) => new DataView(b, o),
      _2174: (b, o, l) => new DataView(b, o, l),
      _2175: Function.prototype.call.bind(DataView.prototype.getUint8),
      _2176: Function.prototype.call.bind(DataView.prototype.setUint8),
      _2177: Function.prototype.call.bind(DataView.prototype.getInt8),
      _2178: Function.prototype.call.bind(DataView.prototype.setInt8),
      _2179: Function.prototype.call.bind(DataView.prototype.getUint16),
      _2180: Function.prototype.call.bind(DataView.prototype.setUint16),
      _2181: Function.prototype.call.bind(DataView.prototype.getInt16),
      _2182: Function.prototype.call.bind(DataView.prototype.setInt16),
      _2183: Function.prototype.call.bind(DataView.prototype.getUint32),
      _2184: Function.prototype.call.bind(DataView.prototype.setUint32),
      _2185: Function.prototype.call.bind(DataView.prototype.getInt32),
      _2186: Function.prototype.call.bind(DataView.prototype.setInt32),
      _2189: Function.prototype.call.bind(DataView.prototype.getBigInt64),
      _2190: Function.prototype.call.bind(DataView.prototype.setBigInt64),
      _2191: Function.prototype.call.bind(DataView.prototype.getFloat32),
      _2192: Function.prototype.call.bind(DataView.prototype.setFloat32),
      _2193: Function.prototype.call.bind(DataView.prototype.getFloat64),
      _2194: Function.prototype.call.bind(DataView.prototype.setFloat64),
      _2195: Function.prototype.call.bind(Number.prototype.toString),
      _2196: Function.prototype.call.bind(BigInt.prototype.toString),
      _2197: Function.prototype.call.bind(Number.prototype.toString),
      _2198: (d, digits) => d.toFixed(digits),
      _2219: () => globalThis.document,
      _2225: (x0,x1) => { x0.height = x1 },
      _2227: (x0,x1) => { x0.width = x1 },
      _2229: (x0,x1) => { x0.pointerEvents = x1 },
      _2238: x0 => x0.style,
      _2241: x0 => x0.src,
      _2242: (x0,x1) => { x0.src = x1 },
      _2243: x0 => x0.naturalWidth,
      _2244: x0 => x0.naturalHeight,
      _2260: x0 => x0.status,
      _2261: (x0,x1) => { x0.responseType = x1 },
      _2263: x0 => x0.response,
      _2312: (x0,x1) => { x0.responseType = x1 },
      _2313: x0 => x0.response,
      _2389: x0 => x0.style,
      _2402: (x0,x1) => { x0.oncancel = x1 },
      _2408: (x0,x1) => { x0.onchange = x1 },
      _2448: (x0,x1) => { x0.onerror = x1 },
      _2821: (x0,x1) => { x0.src = x1 },
      _2832: x0 => x0.width,
      _2834: x0 => x0.height,
      _2866: (x0,x1) => { x0.src = x1 },
      _2996: (x0,x1) => { x0.srcObject = x1 },
      _3020: (x0,x1) => { x0.autoplay = x1 },
      _3315: (x0,x1) => { x0.accept = x1 },
      _3329: x0 => x0.files,
      _3355: (x0,x1) => { x0.multiple = x1 },
      _3373: (x0,x1) => { x0.type = x1 },
      _3623: (x0,x1) => { x0.src = x1 },
      _3625: (x0,x1) => { x0.type = x1 },
      _3631: (x0,x1) => { x0.defer = x1 },
      _3633: (x0,x1) => { x0.crossOrigin = x1 },
      _3635: (x0,x1) => { x0.text = x1 },
      _3668: (x0,x1) => { x0.width = x1 },
      _3670: (x0,x1) => { x0.height = x1 },
      _4090: () => globalThis.window,
      _4130: x0 => x0.location,
      _4149: x0 => x0.navigator,
      _4165: x0 => x0.devicePixelRatio,
      _4411: x0 => x0.trustedTypes,
      _4412: x0 => x0.sessionStorage,
      _4413: x0 => x0.localStorage,
      _4421: x0 => x0.href,
      _4517: x0 => x0.geolocation,
      _4520: x0 => x0.mediaDevices,
      _4522: x0 => x0.permissions,
      _4523: x0 => x0.maxTouchPoints,
      _4530: x0 => x0.appCodeName,
      _4531: x0 => x0.appName,
      _4532: x0 => x0.appVersion,
      _4533: x0 => x0.platform,
      _4534: x0 => x0.product,
      _4535: x0 => x0.productSub,
      _4536: x0 => x0.userAgent,
      _4537: x0 => x0.vendor,
      _4538: x0 => x0.vendorSub,
      _4540: x0 => x0.language,
      _4541: x0 => x0.languages,
      _4542: x0 => x0.onLine,
      _4547: x0 => x0.hardwareConcurrency,
      _4586: x0 => x0.data,
      _4633: (x0,x1) => { x0.onmessage = x1 },
      _4739: x0 => x0.length,
      _4956: x0 => x0.readyState,
      _4969: (x0,x1) => { x0.binaryType = x1 },
      _4972: x0 => x0.code,
      _4973: x0 => x0.reason,
      _5019: x0 => x0.localDescription,
      _5022: x0 => x0.remoteDescription,
      _5025: x0 => x0.signalingState,
      _5026: x0 => x0.iceGatheringState,
      _5027: x0 => x0.iceConnectionState,
      _5028: x0 => x0.connectionState,
      _5041: (x0,x1) => { x0.onicegatheringstatechange = x1 },
      _5053: x0 => x0.type,
      _5054: x0 => x0.sdp,
      _5055: x0 => x0.type,
      _5057: x0 => x0.sdp,
      _5065: x0 => x0.candidate,
      _5066: x0 => x0.sdpMid,
      _5067: x0 => x0.sdpMLineIndex,
      _5089: x0 => x0.candidate,
      _5125: x0 => x0.track,
      _5131: x0 => x0.headerExtensions,
      _5133: x0 => x0.rtcp,
      _5141: (x0,x1) => { x0.encodings = x1 },
      _5149: x0 => x0.active,
      _5164: x0 => x0.cname,
      _5166: x0 => x0.reducedSize,
      _5178: x0 => x0.clockRate,
      _5185: x0 => x0.payloadType,
      _5188: x0 => x0.codecs,
      _5190: x0 => x0.headerExtensions,
      _5215: x0 => x0.sender,
      _5258: x0 => x0.receiver,
      _5259: x0 => x0.track,
      _5260: x0 => x0.streams,
      _5261: x0 => x0.transceiver,
      _5277: x0 => x0.label,
      _5283: x0 => x0.id,
      _5285: x0 => x0.bufferedAmount,
      _5286: x0 => x0.bufferedAmountLowThreshold,
      _5287: (x0,x1) => { x0.bufferedAmountLowThreshold = x1 },
      _5289: (x0,x1) => { x0.onopen = x1 },
      _5291: (x0,x1) => { x0.onbufferedamountlow = x1 },
      _5297: (x0,x1) => { x0.onclose = x1 },
      _5299: (x0,x1) => { x0.onmessage = x1 },
      _5306: (x0,x1) => { x0.maxPacketLifeTime = x1 },
      _5308: (x0,x1) => { x0.maxRetransmits = x1 },
      _5318: x0 => x0.channel,
      _6609: x0 => x0.type,
      _6610: x0 => x0.target,
      _6650: x0 => x0.signal,
      _6705: x0 => x0.isConnected,
      _6721: () => globalThis.document,
      _6802: x0 => x0.body,
      _6804: x0 => x0.head,
      _7132: x0 => x0.id,
      _7133: (x0,x1) => { x0.id = x1 },
      _8479: x0 => x0.value,
      _8481: x0 => x0.done,
      _8660: x0 => x0.size,
      _8661: x0 => x0.type,
      _8667: x0 => x0.name,
      _8668: x0 => x0.lastModified,
      _8673: x0 => x0.length,
      _8679: x0 => x0.result,
      _8898: () => globalThis.Notification.permission,
      _9172: x0 => x0.url,
      _9174: x0 => x0.status,
      _9176: x0 => x0.statusText,
      _9177: x0 => x0.headers,
      _9178: x0 => x0.body,
      _9960: x0 => x0.id,
      _9967: x0 => x0.kind,
      _9968: x0 => x0.id,
      _9969: x0 => x0.label,
      _9970: x0 => x0.enabled,
      _9971: (x0,x1) => { x0.enabled = x1 },
      _9972: x0 => x0.muted,
      _10205: x0 => x0.width,
      _10207: x0 => x0.height,
      _10209: x0 => x0.aspectRatio,
      _10211: x0 => x0.frameRate,
      _10213: x0 => x0.facingMode,
      _10215: x0 => x0.resizeMode,
      _10217: x0 => x0.sampleRate,
      _10219: x0 => x0.sampleSize,
      _10221: x0 => x0.echoCancellation,
      _10223: x0 => x0.autoGainControl,
      _10225: x0 => x0.noiseSuppression,
      _10227: x0 => x0.latency,
      _10229: x0 => x0.channelCount,
      _10231: x0 => x0.deviceId,
      _10233: x0 => x0.groupId,
      _10287: (x0,x1) => { x0.ondevicechange = x1 },
      _10289: x0 => x0.deviceId,
      _10290: x0 => x0.kind,
      _10291: x0 => x0.label,
      _10292: x0 => x0.groupId,
      _11289: (x0,x1) => { x0.border = x1 },
      _11567: (x0,x1) => { x0.display = x1 },
      _11731: (x0,x1) => { x0.height = x1 },
      _12421: (x0,x1) => { x0.width = x1 },
      _12789: x0 => x0.name,
      _13505: () => globalThis.console,
      _13533: () => globalThis.speechSynthesis,
      _13534: (x0,x1) => { x0.lang = x1 },
      _13536: (x0,x1) => { x0.pitch = x1 },
      _13539: (x0,x1) => { x0.rate = x1 },
      _13541: (x0,x1) => { x0.text = x1 },
      _13542: (x0,x1) => { x0.voice = x1 },
      _13543: x0 => x0.voice,
      _13545: (x0,x1) => { x0.volume = x1 },
      _13546: (x0,x1) => { x0.onstart = x1 },
      _13547: (x0,x1) => { x0.onend = x1 },
      _13548: (x0,x1) => { x0.onpause = x1 },
      _13549: (x0,x1) => { x0.onresume = x1 },
      _13550: (x0,x1) => { x0.onerror = x1 },
      _13551: (x0,x1) => { x0.onboundary = x1 },
      _13553: x0 => x0.lang,
      _13554: x0 => x0.localService,
      _13555: x0 => x0.name,
      _13556: x0 => x0.name,
      _13557: x0 => x0.message,
      _13558: x0 => x0.code,

    };

    const baseImports = {
      dart2wasm: dart2wasm,
      Math: Math,
      Date: Date,
      Object: Object,
      Array: Array,
      Reflect: Reflect,
      WebAssembly: {
        JSTag: WebAssembly.JSTag,
      },
      "": new Proxy({}, { get(_, prop) { return prop; } }),

    };

    const jsStringPolyfill = {
      "charCodeAt": (s, i) => s.charCodeAt(i),
      "compare": (s1, s2) => {
        if (s1 < s2) return -1;
        if (s1 > s2) return 1;
        return 0;
      },
      "concat": (s1, s2) => s1 + s2,
      "equals": (s1, s2) => s1 === s2,
      "fromCharCode": (i) => String.fromCharCode(i),
      "length": (s) => s.length,
      "substring": (s, a, b) => s.substring(a, b),
      "fromCharCodeArray": (a, start, end) => {
        if (end <= start) return '';

        const read = dartInstance.exports.$wasmI16ArrayGet;
        let result = '';
        let index = start;
        const chunkLength = Math.min(end - index, 500);
        let array = new Array(chunkLength);
        while (index < end) {
          const newChunkLength = Math.min(end - index, 500);
          for (let i = 0; i < newChunkLength; i++) {
            array[i] = read(a, index++);
          }
          if (newChunkLength < chunkLength) {
            array = array.slice(0, newChunkLength);
          }
          result += String.fromCharCode(...array);
        }
        return result;
      },
      "intoCharCodeArray": (s, a, start) => {
        if (s === '') return 0;

        const write = dartInstance.exports.$wasmI16ArraySet;
        for (var i = 0; i < s.length; ++i) {
          write(a, start++, s.charCodeAt(i));
        }
        return s.length;
      },
      "test": (s) => typeof s == "string",
    };


    

    dartInstance = await WebAssembly.instantiate(this.module, {
      ...baseImports,
      ...additionalImports,
      
      "wasm:js-string": jsStringPolyfill,
    });
    dartInstance.exports.$setThisModule(dartInstance);

    return new InstantiatedApp(this, dartInstance);
  }
}

class InstantiatedApp {
  constructor(compiledApp, instantiatedModule) {
    this.compiledApp = compiledApp;
    this.instantiatedModule = instantiatedModule;
  }

  // Call the main function with the given arguments.
  invokeMain(...args) {
    this.instantiatedModule.exports.$invokeMain(args);
  }
}
