// Compiles a dart2wasm-generated main module from `source` which can then
// instantiatable via the `instantiate` method.
//
// `source` needs to be a `Response` object (or promise thereof) e.g. created
// via the `fetch()` JS API.
export async function compileStreaming(source) {
  const builtins = {builtins: ['js-string']};
  return new CompiledApp(
      await WebAssembly.compileStreaming(source, builtins), builtins);
}

// Compiles a dart2wasm-generated wasm modules from `bytes` which is then
// instantiatable via the `instantiate` method.
export async function compile(bytes) {
  const builtins = {builtins: ['js-string']};
  return new CompiledApp(await WebAssembly.compile(bytes, builtins), builtins);
}

// DEPRECATED: Please use `compile` or `compileStreaming` to get a compiled app,
// use `instantiate` method to get an instantiated app and then call
// `invokeMain` to invoke the main function.
export async function instantiate(modulePromise, importObjectPromise) {
  var moduleOrCompiledApp = await modulePromise;
  if (!(moduleOrCompiledApp instanceof CompiledApp)) {
    moduleOrCompiledApp = new CompiledApp(moduleOrCompiledApp);
  }
  const instantiatedApp = await moduleOrCompiledApp.instantiate(await importObjectPromise);
  return instantiatedApp.instantiatedModule;
}

// DEPRECATED: Please use `compile` or `compileStreaming` to get a compiled app,
// use `instantiate` method to get an instantiated app and then call
// `invokeMain` to invoke the main function.
export const invoke = (moduleInstance, ...args) => {
  moduleInstance.exports.$invokeMain(args);
}

class CompiledApp {
  constructor(module, builtins) {
    this.module = module;
    this.builtins = builtins;
  }

  // The second argument is an options object containing:
  // `loadDeferredModule` is a JS function that takes a module name matching a
  //   wasm file produced by the dart2wasm compiler and returns the bytes to
  //   load the module. These bytes can be in either a format supported by
  //   `WebAssembly.compile` or `WebAssembly.compileStreaming`.
  // `loadDynamicModule` is a JS function that takes two string names matching,
  //   in order, a wasm file produced by the dart2wasm compiler during dynamic
  //   module compilation and a corresponding js file produced by the same
  //   compilation. It should return a JS Array containing 2 elements. The first
  //   should be the bytes for the wasm module in a format supported by
  //   `WebAssembly.compile` or `WebAssembly.compileStreaming`. The second
  //   should be the result of using the JS 'import' API on the js file path.
  // `loadDeferredId` is a JS function that takes a string corresponding to a load
  //   ID generated by the compiler when 'load-ids' option is passed. Each load
  //   ID maps to one or more WASM modules produced by the compiler. This
  //   function should return an array of byte arrays corresponding to all the
  //   modules specified by that load ID. The arrays should be in a format
  //   supported by `WebAssembly.compile` or `WebAssembly.compileStreaming`.
  async instantiate(additionalImports,
      {loadDeferredModule, loadDynamicModule, loadDeferredId} = {}) {
    let dartInstance;

    // Prints to the console
    function printToConsole(value) {
      if (typeof dartPrint == "function") {
        dartPrint(value);
        return;
      }
      if (typeof console == "object" && typeof console.log != "undefined") {
        console.log(value);
        return;
      }
      if (typeof print == "function") {
        print(value);
        return;
      }

      throw "Unable to print message: " + value;
    }

    // A special symbol attached to functions that wrap Dart functions.
    const jsWrappedDartFunctionSymbol = Symbol("JSWrappedDartFunction");

    function finalizeWrapper(dartFunction, wrapped) {
      wrapped.dartFunction = dartFunction;
      wrapped[jsWrappedDartFunctionSymbol] = true;
      return wrapped;
    }

    // Imports
    const dart2wasm = {
            _1: (decoder, codeUnits) => decoder.decode(codeUnits),
      _2: () => new TextDecoder("utf-8", {fatal: true}),
      _3: () => new TextDecoder("utf-8", {fatal: false}),
      _4: (s) => +s,
      _5: x0 => new Uint8Array(x0),
      _6: (x0,x1,x2) => x0.set(x1,x2),
      _7: (x0,x1) => x0.transferFromImageBitmap(x1),
      _9: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._9(f,arguments.length,x0) }),
      _10: x0 => new window.FinalizationRegistry(x0),
      _11: (x0,x1,x2,x3) => x0.register(x1,x2,x3),
      _12: (x0,x1) => x0.unregister(x1),
      _13: (x0,x1,x2) => x0.slice(x1,x2),
      _14: (x0,x1) => x0.decode(x1),
      _15: (x0,x1) => x0.segment(x1),
      _16: () => new TextDecoder(),
      _18: x0 => x0.buffer,
      _19: x0 => x0.wasmMemory,
      _20: () => globalThis.window._flutter_skwasmInstance,
      _21: x0 => x0.rasterStartMilliseconds,
      _22: x0 => x0.rasterEndMilliseconds,
      _23: x0 => x0.imageBitmaps,
      _139: (x0,x1) => x0.appendChild(x1),
      _170: (x0,x1,x2) => x0.addEventListener(x1,x2),
      _171: (x0,x1,x2) => x0.removeEventListener(x1,x2),
      _172: (x0,x1) => new OffscreenCanvas(x0,x1),
      _173: x0 => x0.remove(),
      _174: (x0,x1) => x0.append(x1),
      _176: x0 => x0.unlock(),
      _177: x0 => x0.getReader(),
      _178: (x0,x1) => x0.item(x1),
      _179: x0 => x0.next(),
      _180: x0 => x0.now(),
      _181: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._181(f,arguments.length,x0) }),
      _182: (x0,x1) => x0.addListener(x1),
      _183: (x0,x1) => x0.removeListener(x1),
      _184: (x0,x1) => x0.matchMedia(x1),
      _185: (x0,x1) => x0.revokeObjectURL(x1),
      _186: x0 => x0.close(),
      _187: (x0,x1,x2,x3,x4) => ({type: x0,data: x1,premultiplyAlpha: x2,colorSpaceConversion: x3,preferAnimation: x4}),
      _188: x0 => new window.ImageDecoder(x0),
      _189: (x0,x1) => ({frameIndex: x0,completeFramesOnly: x1}),
      _190: (x0,x1) => x0.decode(x1),
      _191: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._191(f,arguments.length,x0) }),
      _192: (x0,x1,x2,x3) => x0.addEventListener(x1,x2,x3),
      _194: (x0,x1) => x0.getModifierState(x1),
      _195: x0 => x0.preventDefault(),
      _196: x0 => x0.stopPropagation(),
      _197: (x0,x1) => x0.removeProperty(x1),
      _198: (x0,x1) => x0.prepend(x1),
      _199: x0 => new Intl.Locale(x0),
      _200: (x0,x1) => x0.observe(x1),
      _201: x0 => x0.disconnect(),
      _202: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._202(f,arguments.length,x0) }),
      _203: (x0,x1) => x0.getAttribute(x1),
      _204: (x0,x1) => x0.contains(x1),
      _205: (x0,x1) => x0.querySelector(x1),
      _206: x0 => x0.blur(),
      _207: x0 => x0.hasFocus(),
      _208: (x0,x1) => x0.removeAttribute(x1),
      _209: (x0,x1,x2) => x0.insertBefore(x1,x2),
      _210: (x0,x1) => x0.hasAttribute(x1),
      _211: (x0,x1) => x0.getModifierState(x1),
      _212: (x0,x1) => x0.createTextNode(x1),
      _213: x0 => x0.getBoundingClientRect(),
      _214: (x0,x1) => x0.closest(x1),
      _215: () => new Array(),
      _651: x0 => new Uint8Array(x0),
      _655: () => globalThis.window.flutterConfiguration,
      _657: x0 => x0.assetBase,
      _662: x0 => x0.canvasKitMaximumSurfaces,
      _663: x0 => x0.debugShowSemanticsNodes,
      _664: x0 => x0.hostElement,
      _665: x0 => x0.multiViewEnabled,
      _666: x0 => x0.nonce,
      _668: x0 => x0.fontFallbackBaseUrl,
      _678: x0 => x0.console,
      _679: x0 => x0.devicePixelRatio,
      _680: x0 => x0.document,
      _681: x0 => x0.history,
      _682: x0 => x0.innerHeight,
      _683: x0 => x0.innerWidth,
      _684: x0 => x0.location,
      _685: x0 => x0.navigator,
      _686: x0 => x0.visualViewport,
      _687: x0 => x0.performance,
      _689: x0 => x0.URL,
      _691: (x0,x1) => x0.getComputedStyle(x1),
      _692: x0 => x0.screen,
      _693: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._693(f,arguments.length,x0) }),
      _694: (x0,x1) => x0.requestAnimationFrame(x1),
      _698: (x0,x1) => x0.warn(x1),
      _700: (x0,x1) => x0.debug(x1),
      _701: x0 => globalThis.parseFloat(x0),
      _702: () => globalThis.window,
      _703: () => globalThis.Intl,
      _704: () => globalThis.Symbol,
      _705: (x0,x1,x2,x3,x4) => globalThis.createImageBitmap(x0,x1,x2,x3,x4),
      _707: x0 => x0.clipboard,
      _708: x0 => x0.maxTouchPoints,
      _709: x0 => x0.vendor,
      _710: x0 => x0.language,
      _711: x0 => x0.platform,
      _712: x0 => x0.userAgent,
      _713: (x0,x1) => x0.vibrate(x1),
      _714: x0 => x0.languages,
      _715: x0 => x0.documentElement,
      _716: (x0,x1) => x0.querySelector(x1),
      _717: (x0,x1) => x0.querySelectorAll(x1),
      _719: (x0,x1) => x0.createElement(x1),
      _722: (x0,x1) => x0.createEvent(x1),
      _723: x0 => x0.activeElement,
      _726: x0 => x0.head,
      _727: x0 => x0.body,
      _728: (x0,x1) => { x0.title = x1 },
      _732: x0 => x0.visibilityState,
      _733: () => globalThis.document,
      _734: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._734(f,arguments.length,x0) }),
      _735: (x0,x1) => x0.dispatchEvent(x1),
      _743: x0 => x0.target,
      _745: x0 => x0.timeStamp,
      _746: x0 => x0.type,
      _748: (x0,x1,x2,x3) => x0.initEvent(x1,x2,x3),
      _755: x0 => x0.firstChild,
      _759: x0 => x0.parentElement,
      _761: (x0,x1) => { x0.textContent = x1 },
      _762: x0 => x0.parentNode,
      _763: x0 => x0.nextSibling,
      _764: (x0,x1) => x0.removeChild(x1),
      _765: x0 => x0.isConnected,
      _773: x0 => x0.clientHeight,
      _774: x0 => x0.clientWidth,
      _775: x0 => x0.offsetHeight,
      _776: x0 => x0.offsetWidth,
      _777: x0 => x0.id,
      _778: (x0,x1) => { x0.id = x1 },
      _781: (x0,x1) => { x0.spellcheck = x1 },
      _782: x0 => x0.tagName,
      _783: x0 => x0.style,
      _786: (x0,x1) => x0.querySelectorAll(x1),
      _787: (x0,x1,x2) => x0.setAttribute(x1,x2),
      _788: (x0,x1) => { x0.tabIndex = x1 },
      _789: x0 => x0.tabIndex,
      _790: (x0,x1) => x0.focus(x1),
      _791: x0 => x0.scrollTop,
      _792: (x0,x1) => { x0.scrollTop = x1 },
      _793: x0 => x0.scrollLeft,
      _794: (x0,x1) => { x0.scrollLeft = x1 },
      _795: x0 => x0.classList,
      _797: (x0,x1) => { x0.className = x1 },
      _799: (x0,x1) => x0.getElementsByClassName(x1),
      _800: x0 => x0.click(),
      _801: (x0,x1) => x0.attachShadow(x1),
      _804: x0 => x0.computedStyleMap(),
      _805: (x0,x1) => x0.get(x1),
      _811: (x0,x1) => x0.getPropertyValue(x1),
      _812: (x0,x1,x2,x3) => x0.setProperty(x1,x2,x3),
      _813: x0 => x0.offsetLeft,
      _814: x0 => x0.offsetTop,
      _815: x0 => x0.offsetParent,
      _817: (x0,x1) => { x0.name = x1 },
      _818: x0 => x0.content,
      _819: (x0,x1) => { x0.content = x1 },
      _823: (x0,x1) => { x0.src = x1 },
      _824: x0 => x0.naturalWidth,
      _825: x0 => x0.naturalHeight,
      _829: (x0,x1) => { x0.crossOrigin = x1 },
      _831: (x0,x1) => { x0.decoding = x1 },
      _832: x0 => x0.decode(),
      _837: (x0,x1) => { x0.nonce = x1 },
      _841: (x0,x1) => { x0.width = x1 },
      _844: (x0,x1) => { x0.height = x1 },
      _847: (x0,x1) => x0.getContext(x1),
      _914: x0 => x0.width,
      _915: x0 => x0.height,
      _917: (x0,x1) => x0.fetch(x1),
      _918: x0 => x0.status,
      _920: x0 => x0.body,
      _921: x0 => x0.arrayBuffer(),
      _924: x0 => x0.read(),
      _925: x0 => x0.value,
      _926: x0 => x0.done,
      _933: x0 => x0.name,
      _934: x0 => x0.x,
      _935: x0 => x0.y,
      _938: x0 => x0.top,
      _939: x0 => x0.right,
      _940: x0 => x0.bottom,
      _941: x0 => x0.left,
      _951: x0 => x0.height,
      _952: x0 => x0.width,
      _953: x0 => x0.scale,
      _954: (x0,x1) => { x0.value = x1 },
      _957: (x0,x1) => { x0.placeholder = x1 },
      _959: (x0,x1) => { x0.name = x1 },
      _960: x0 => x0.selectionDirection,
      _961: x0 => x0.selectionStart,
      _962: x0 => x0.selectionEnd,
      _965: x0 => x0.value,
      _967: (x0,x1,x2) => x0.setSelectionRange(x1,x2),
      _968: x0 => x0.readText(),
      _969: (x0,x1) => x0.writeText(x1),
      _971: x0 => x0.altKey,
      _972: x0 => x0.code,
      _973: x0 => x0.ctrlKey,
      _974: x0 => x0.key,
      _975: x0 => x0.keyCode,
      _976: x0 => x0.location,
      _977: x0 => x0.metaKey,
      _978: x0 => x0.repeat,
      _979: x0 => x0.shiftKey,
      _980: x0 => x0.isComposing,
      _982: x0 => x0.state,
      _983: (x0,x1) => x0.go(x1),
      _985: (x0,x1,x2,x3) => x0.pushState(x1,x2,x3),
      _986: (x0,x1,x2,x3) => x0.replaceState(x1,x2,x3),
      _987: x0 => x0.pathname,
      _988: x0 => x0.search,
      _989: x0 => x0.hash,
      _993: x0 => x0.state,
      _996: (x0,x1) => x0.createObjectURL(x1),
      _998: x0 => new Blob(x0),
      _1008: x0 => x0.matches,
      _1009: x0 => x0.matches,
      _1013: x0 => x0.relatedTarget,
      _1015: x0 => x0.clientX,
      _1016: x0 => x0.clientY,
      _1017: x0 => x0.offsetX,
      _1018: x0 => x0.offsetY,
      _1021: x0 => x0.button,
      _1022: x0 => x0.buttons,
      _1023: x0 => x0.ctrlKey,
      _1027: x0 => x0.pointerId,
      _1028: x0 => x0.pointerType,
      _1029: x0 => x0.pressure,
      _1030: x0 => x0.tiltX,
      _1031: x0 => x0.tiltY,
      _1032: x0 => x0.getCoalescedEvents(),
      _1035: x0 => x0.deltaX,
      _1036: x0 => x0.deltaY,
      _1037: x0 => x0.wheelDeltaX,
      _1038: x0 => x0.wheelDeltaY,
      _1039: x0 => x0.deltaMode,
      _1046: x0 => x0.changedTouches,
      _1049: x0 => x0.clientX,
      _1050: x0 => x0.clientY,
      _1053: x0 => x0.data,
      _1056: (x0,x1) => { x0.disabled = x1 },
      _1058: (x0,x1) => { x0.type = x1 },
      _1059: (x0,x1) => { x0.max = x1 },
      _1060: (x0,x1) => { x0.min = x1 },
      _1061: (x0,x1) => { x0.value = x1 },
      _1062: x0 => x0.value,
      _1063: x0 => x0.disabled,
      _1064: (x0,x1) => { x0.disabled = x1 },
      _1066: (x0,x1) => { x0.placeholder = x1 },
      _1068: (x0,x1) => { x0.name = x1 },
      _1069: (x0,x1) => { x0.autocomplete = x1 },
      _1071: x0 => x0.selectionDirection,
      _1072: x0 => x0.selectionStart,
      _1074: x0 => x0.selectionEnd,
      _1077: (x0,x1,x2) => x0.setSelectionRange(x1,x2),
      _1078: (x0,x1) => x0.add(x1),
      _1081: (x0,x1) => { x0.noValidate = x1 },
      _1082: (x0,x1) => { x0.method = x1 },
      _1083: (x0,x1) => { x0.action = x1 },
      _1108: x0 => x0.orientation,
      _1109: x0 => x0.width,
      _1110: x0 => x0.height,
      _1111: (x0,x1) => x0.lock(x1),
      _1130: x0 => new ResizeObserver(x0),
      _1133: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1133(f,arguments.length,x0,x1) }),
      _1141: x0 => x0.length,
      _1142: x0 => x0.iterator,
      _1143: x0 => x0.Segmenter,
      _1144: x0 => x0.v8BreakIterator,
      _1145: (x0,x1) => new Intl.Segmenter(x0,x1),
      _1148: x0 => x0.language,
      _1149: x0 => x0.script,
      _1150: x0 => x0.region,
      _1168: x0 => x0.done,
      _1169: x0 => x0.value,
      _1170: x0 => x0.index,
      _1174: (x0,x1) => new Intl.v8BreakIterator(x0,x1),
      _1175: (x0,x1) => x0.adoptText(x1),
      _1176: x0 => x0.first(),
      _1177: x0 => x0.next(),
      _1178: x0 => x0.current(),
      _1191: x0 => x0.hostElement,
      _1192: x0 => x0.viewConstraints,
      _1195: x0 => x0.maxHeight,
      _1196: x0 => x0.maxWidth,
      _1197: x0 => x0.minHeight,
      _1198: x0 => x0.minWidth,
      _1199: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1199(f,arguments.length,x0) }),
      _1200: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1200(f,arguments.length,x0) }),
      _1201: (x0,x1) => ({addView: x0,removeView: x1}),
      _1204: x0 => x0.loader,
      _1205: () => globalThis._flutter,
      _1206: (x0,x1) => x0.didCreateEngineInitializer(x1),
      _1207: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1207(f,arguments.length,x0) }),
      _1208: (module,f) => finalizeWrapper(f, function() { return module.exports._1208(f,arguments.length) }),
      _1209: (x0,x1) => ({initializeEngine: x0,autoStart: x1}),
      _1212: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1212(f,arguments.length,x0) }),
      _1213: x0 => ({runApp: x0}),
      _1215: (x0,x1,x2) => x0.call(x1,x2),
      _1216: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1216(f,arguments.length,x0,x1) }),
      _1217: x0 => new Promise(x0),
      _1218: x0 => x0.length,
      _1219: () => globalThis.window.ImageDecoder,
      _1220: x0 => x0.tracks,
      _1222: x0 => x0.completed,
      _1224: x0 => x0.image,
      _1230: x0 => x0.displayWidth,
      _1231: x0 => x0.displayHeight,
      _1232: x0 => x0.duration,
      _1235: x0 => x0.ready,
      _1236: x0 => x0.selectedTrack,
      _1237: x0 => x0.repetitionCount,
      _1238: x0 => x0.frameCount,
      _1281: (x0,x1) => x0.getElementById(x1),
      _1307: x0 => new Float32Array(x0),
      _1309: x0 => x0.close(),
      _1310: (x0,x1) => x0.send(x1),
      _1311: x0 => new WebSocket(x0),
      _1312: () => new MediaStream(),
      _1313: x0 => x0.getVideoTracks(),
      _1314: (x0,x1) => x0.addTrack(x1),
      _1315: x0 => x0.getAudioTracks(),
      _1316: (x0,x1) => x0.append(x1),
      _1319: x0 => x0.remove(),
      _1322: (x0,x1) => x0.appendChild(x1),
      _1323: x0 => x0.play(),
      _1338: (x0,x1) => x0.createElement(x1),
      _1344: (x0,x1,x2) => x0.addEventListener(x1,x2),
      _1345: (x0,x1) => x0.get(x1),
      _1346: x0 => x0.text(),
      _1352: (x0,x1,x2,x3) => x0.addEventListener(x1,x2,x3),
      _1353: (x0,x1,x2,x3) => x0.removeEventListener(x1,x2,x3),
      _1354: (x0,x1) => x0.createElement(x1),
      _1372: () => globalThis.Notification.requestPermission(),
      _1373: x0 => x0.decode(),
      _1374: (x0,x1,x2,x3) => x0.open(x1,x2,x3),
      _1375: (x0,x1,x2) => x0.setRequestHeader(x1,x2),
      _1376: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1376(f,arguments.length,x0) }),
      _1377: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1377(f,arguments.length,x0) }),
      _1378: x0 => x0.send(),
      _1379: () => new XMLHttpRequest(),
      _1380: (x0,x1) => x0.getItem(x1),
      _1381: (x0,x1) => x0.removeItem(x1),
      _1382: (x0,x1,x2) => x0.setItem(x1,x2),
      _1386: (x0,x1) => x0.getUserMedia(x1),
      _1387: x0 => x0.stop(),
      _1394: x0 => x0.deviceMemory,
      _1396: (x0,x1,x2,x3,x4,x5,x6,x7) => ({apiKey: x0,authDomain: x1,databaseURL: x2,projectId: x3,storageBucket: x4,messagingSenderId: x5,measurementId: x6,appId: x7}),
      _1397: (x0,x1) => globalThis.firebase_core.initializeApp(x0,x1),
      _1398: x0 => globalThis.firebase_core.getApp(x0),
      _1399: () => globalThis.firebase_core.getApp(),
      _1400: (x0,x1,x2) => globalThis.firebase_core.registerVersion(x0,x1,x2),
      _1402: x0 => globalThis.firebase_messaging.getMessaging(x0),
      _1404: (x0,x1) => globalThis.firebase_messaging.getToken(x0,x1),
      _1406: (x0,x1) => globalThis.firebase_messaging.onMessage(x0,x1),
      _1407: (x0,x1) => ({next: x0,error: x1}),
      _1410: x0 => ({vapidKey: x0}),
      _1412: x0 => x0.title,
      _1413: x0 => x0.body,
      _1414: x0 => x0.image,
      _1415: x0 => x0.messageId,
      _1416: x0 => x0.collapseKey,
      _1417: x0 => x0.fcmOptions,
      _1418: x0 => x0.notification,
      _1419: x0 => x0.data,
      _1420: x0 => x0.from,
      _1421: x0 => x0.analyticsLabel,
      _1422: x0 => x0.link,
      _1423: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1423(f,arguments.length,x0) }),
      _1424: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1424(f,arguments.length,x0) }),
      _1426: () => globalThis.firebase_core.SDK_VERSION,
      _1432: x0 => x0.apiKey,
      _1434: x0 => x0.authDomain,
      _1436: x0 => x0.databaseURL,
      _1438: x0 => x0.projectId,
      _1440: x0 => x0.storageBucket,
      _1442: x0 => x0.messagingSenderId,
      _1444: x0 => x0.measurementId,
      _1446: x0 => x0.appId,
      _1448: x0 => x0.name,
      _1449: x0 => x0.options,
      _1450: (x0,x1) => x0.debug(x1),
      _1451: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1451(f,arguments.length,x0) }),
      _1452: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1452(f,arguments.length,x0,x1) }),
      _1453: (x0,x1) => ({createScript: x0,createScriptURL: x1}),
      _1454: (x0,x1,x2) => x0.createPolicy(x1,x2),
      _1455: (x0,x1) => x0.createScriptURL(x1),
      _1456: (x0,x1,x2) => x0.createScript(x1,x2),
      _1457: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1457(f,arguments.length,x0) }),
      _1458: () => new SpeechSynthesisUtterance(),
      _1459: x0 => x0.pause(),
      _1460: x0 => x0.resume(),
      _1461: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1461(f,arguments.length,x0) }),
      _1462: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1462(f,arguments.length,x0) }),
      _1463: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1463(f,arguments.length,x0) }),
      _1464: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1464(f,arguments.length,x0) }),
      _1465: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1465(f,arguments.length,x0) }),
      _1466: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1466(f,arguments.length,x0) }),
      _1467: (x0,x1) => x0.speak(x1),
      _1468: x0 => x0.cancel(),
      _1469: x0 => x0.getVoices(),
      _1474: Date.now,
      _1476: s => new Date(s * 1000).getTimezoneOffset() * 60,
      _1477: s => {
        if (!/^\s*[+-]?(?:Infinity|NaN|(?:\.\d+|\d+(?:\.\d*)?)(?:[eE][+-]?\d+)?)\s*$/.test(s)) {
          return NaN;
        }
        return parseFloat(s);
      },
      _1478: () => new Error().stack,
      _1479: () => typeof dartUseDateNowForTicks !== "undefined",
      _1480: () => 1000 * performance.now(),
      _1481: () => Date.now(),
      _1482: () => {
        // On browsers return `globalThis.location.href`
        if (globalThis.location != null) {
          return globalThis.location.href;
        }
        return null;
      },
      _1483: () => {
        return typeof process != "undefined" &&
               Object.prototype.toString.call(process) == "[object process]" &&
               process.platform == "win32"
      },
      _1484: () => new WeakMap(),
      _1485: (map, o) => map.get(o),
      _1486: (map, o, v) => map.set(o, v),
      _1487: (exn) => exn.toString(),
      _1488: (exn) => exn.stack,
      _1489: (exn) => {
        let stackString = exn.toString();
        let frames = stackString.split('\n');
        let drop = 2;
        if (frames[0] === 'Error') {
            drop += 1;
        }
        return frames.slice(drop).join('\n');
      },
      _1490: x0 => new WeakRef(x0),
      _1491: x0 => x0.deref(),
      _1498: () => globalThis.WeakRef,
      _1501: s => JSON.stringify(s),
      _1502: s => printToConsole(s),
      _1503: (o, p, r) => o.replaceAll(p, () => r),
      _1504: (o, p, r) => o.replace(p, () => r),
      _1505: Function.prototype.call.bind(String.prototype.toLowerCase),
      _1506: s => s.toUpperCase(),
      _1507: s => s.trim(),
      _1508: s => s.trimLeft(),
      _1509: s => s.trimRight(),
      _1510: (string, times) => string.repeat(times),
      _1511: Function.prototype.call.bind(String.prototype.indexOf),
      _1512: (s, p, i) => s.lastIndexOf(p, i),
      _1513: (string, token) => string.split(token),
      _1514: Object.is,
      _1517: (o, t) => typeof o === t,
      _1518: (o, c) => o instanceof c,
      _1519: o => Object.keys(o),
      _1549: x0 => new Array(x0),
      _1551: x0 => x0.length,
      _1553: (x0,x1) => x0[x1],
      _1554: (x0,x1,x2) => { x0[x1] = x2 },
      _1557: (x0,x1,x2) => new DataView(x0,x1,x2),
      _1559: x0 => new Int8Array(x0),
      _1560: (x0,x1,x2) => new Uint8Array(x0,x1,x2),
      _1562: x0 => new Uint8ClampedArray(x0),
      _1564: x0 => new Int16Array(x0),
      _1566: x0 => new Uint16Array(x0),
      _1568: x0 => new Int32Array(x0),
      _1570: x0 => new Uint32Array(x0),
      _1573: x0 => new Float64Array(x0),
      _1597: x0 => x0.random(),
      _1598: (x0,x1) => x0.getRandomValues(x1),
      _1599: () => globalThis.crypto,
      _1600: () => globalThis.Math,
      _1613: (ms, c) =>
      setTimeout(() => dartInstance.exports.$invokeCallback(c),ms),
      _1614: (handle) => clearTimeout(handle),
      _1615: (ms, c) =>
      setInterval(() => dartInstance.exports.$invokeCallback(c), ms),
      _1616: (handle) => clearInterval(handle),
      _1617: (c) =>
      queueMicrotask(() => dartInstance.exports.$invokeCallback(c)),
      _1618: () => Date.now(),
      _1619: (s, m) => {
        try {
          return new RegExp(s, m);
        } catch (e) {
          return String(e);
        }
      },
      _1620: (x0,x1) => x0.exec(x1),
      _1621: (x0,x1) => x0.test(x1),
      _1622: x0 => x0.pop(),
      _1624: o => o === undefined,
      _1626: o => typeof o === 'function' && o[jsWrappedDartFunctionSymbol] === true,
      _1628: o => {
        const proto = Object.getPrototypeOf(o);
        return proto === Object.prototype || proto === null;
      },
      _1629: o => o instanceof RegExp,
      _1630: (l, r) => l === r,
      _1631: o => o,
      _1632: o => o,
      _1633: o => o,
      _1634: b => !!b,
      _1635: o => o.length,
      _1637: (o, i) => o[i],
      _1638: f => f.dartFunction,
      _1639: () => ({}),
      _1640: () => [],
      _1642: () => globalThis,
      _1643: (constructor, args) => {
        const factoryFunction = constructor.bind.apply(
            constructor, [null, ...args]);
        return new factoryFunction();
      },
      _1645: (o, p) => o[p],
      _1646: (o, p, v) => o[p] = v,
      _1647: (o, m, a) => o[m].apply(o, a),
      _1649: o => String(o),
      _1650: (p, s, f) => p.then(s, (e) => f(e, e === undefined)),
      _1651: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1651(f,arguments.length,x0) }),
      _1652: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1652(f,arguments.length,x0,x1) }),
      _1653: o => {
        if (o === undefined) return 1;
        var type = typeof o;
        if (type === 'boolean') return 2;
        if (type === 'number') return 3;
        if (type === 'string') return 4;
        if (o instanceof Array) return 5;
        if (ArrayBuffer.isView(o)) {
          if (o instanceof Int8Array) return 6;
          if (o instanceof Uint8Array) return 7;
          if (o instanceof Uint8ClampedArray) return 8;
          if (o instanceof Int16Array) return 9;
          if (o instanceof Uint16Array) return 10;
          if (o instanceof Int32Array) return 11;
          if (o instanceof Uint32Array) return 12;
          if (o instanceof Float32Array) return 13;
          if (o instanceof Float64Array) return 14;
          if (o instanceof DataView) return 15;
        }
        if (o instanceof ArrayBuffer) return 16;
        // Feature check for `SharedArrayBuffer` before doing a type-check.
        if (globalThis.SharedArrayBuffer !== undefined &&
            o instanceof SharedArrayBuffer) {
            return 17;
        }
        if (o instanceof Promise) return 18;
        return 19;
      },
      _1654: o => [o],
      _1655: (o0, o1) => [o0, o1],
      _1656: (o0, o1, o2) => [o0, o1, o2],
      _1657: (o0, o1, o2, o3) => [o0, o1, o2, o3],
      _1658: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI8ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1659: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI8ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1660: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI16ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1661: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI16ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1662: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI32ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1663: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI32ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1664: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmF32ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1665: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmF32ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1666: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmF64ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1667: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmF64ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1668: x0 => new ArrayBuffer(x0),
      _1669: s => {
        if (/[[\]{}()*+?.\\^$|]/.test(s)) {
            s = s.replace(/[[\]{}()*+?.\\^$|]/g, '\\$&');
        }
        return s;
      },
      _1670: x0 => x0.input,
      _1671: x0 => x0.index,
      _1673: x0 => x0.flags,
      _1674: x0 => x0.multiline,
      _1675: x0 => x0.ignoreCase,
      _1676: x0 => x0.unicode,
      _1677: x0 => x0.dotAll,
      _1678: (x0,x1) => { x0.lastIndex = x1 },
      _1679: (o, p) => p in o,
      _1680: (o, p) => o[p],
      _1681: (o, p, v) => o[p] = v,
      _1682: (o, p) => delete o[p],
      _1683: (x0,x1) => x0.replaceTrack(x1),
      _1684: x0 => x0.getParameters(),
      _1685: (x0,x1) => x0.setParameters(x1),
      _1686: x0 => x0.getStats(),
      _1687: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1687(f,arguments.length,x0,x1) }),
      _1689: (x0,x1) => x0.setCodecPreferences(x1),
      _1690: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1690(f,arguments.length,x0) }),
      _1691: (x0,x1,x2) => x0.addEventListener(x1,x2),
      _1692: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1692(f,arguments.length,x0) }),
      _1693: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1693(f,arguments.length,x0) }),
      _1694: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1694(f,arguments.length,x0) }),
      _1695: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1695(f,arguments.length,x0) }),
      _1696: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1696(f,arguments.length,x0) }),
      _1697: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1697(f,arguments.length,x0) }),
      _1698: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1698(f,arguments.length,x0) }),
      _1699: x0 => x0.close(),
      _1700: (x0,x1) => x0.setConfiguration(x1),
      _1701: (x0,x1) => x0.createOffer(x1),
      _1702: (x0,x1) => x0.createAnswer(x1),
      _1705: (x0,x1) => ({type: x0,sdp: x1}),
      _1706: (x0,x1) => x0.setLocalDescription(x1),
      _1707: (x0,x1) => ({type: x0,sdp: x1}),
      _1708: (x0,x1) => x0.setRemoteDescription(x1),
      _1709: (x0,x1,x2) => ({candidate: x0,sdpMid: x1,sdpMLineIndex: x2}),
      _1710: (x0,x1) => x0.addIceCandidate(x1),
      _1712: x0 => x0.getStats(),
      _1713: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1713(f,arguments.length,x0,x1) }),
      _1716: (x0,x1,x2,x3) => ({ordered: x0,protocol: x1,negotiated: x2,id: x3}),
      _1717: (x0,x1,x2) => x0.createDataChannel(x1,x2),
      _1718: x0 => x0.restartIce(),
      _1721: (x0,x1) => x0.removeTrack(x1),
      _1722: x0 => x0.getSenders(),
      _1725: (x0,x1,x2) => x0.addTransceiver(x1,x2),
      _1727: (x0,x1) => { x0.binaryType = x1 },
      _1729: x0 => globalThis.RTCRtpReceiver.getCapabilities(x0),
      _1730: x0 => new RTCPeerConnection(x0),
      _1739: x0 => x0.getStats(),
      _1740: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1740(f,arguments.length,x0,x1) }),
      _1742: (x0,x1) => ({video: x0,audio: x1}),
      _1743: (x0,x1) => x0.getDisplayMedia(x1),
      _1744: x0 => x0.enumerateDevices(),
      _1746: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1746(f,arguments.length,x0) }),
      _1754: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1754(f,arguments.length,x0) }),
      _1755: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1755(f,arguments.length,x0) }),
      _1756: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1756(f,arguments.length,x0) }),
      _1759: x0 => x0.getSettings(),
      _1766: x0 => x0.arrayBuffer(),
      _1779: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1779(f,arguments.length,x0) }),
      _1780: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1780(f,arguments.length,x0) }),
      _1786: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1786(f,arguments.length,x0) }),
      _1787: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1787(f,arguments.length,x0) }),
      _1788: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1788(f,arguments.length,x0) }),
      _1789: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1789(f,arguments.length,x0) }),
      _1790: (x0,x1) => x0.send(x1),
      _1792: (x0,x1) => new WebSocket(x0,x1),
      _1793: (x0,x1,x2) => x0.close(x1,x2),
      _1794: (x0,x1) => x0.close(x1),
      _1801: () => new AbortController(),
      _1802: x0 => x0.abort(),
      _1803: (x0,x1,x2,x3,x4,x5) => ({method: x0,headers: x1,body: x2,credentials: x3,redirect: x4,signal: x5}),
      _1804: (x0,x1) => globalThis.fetch(x0,x1),
      _1805: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._1805(f,arguments.length,x0,x1,x2) }),
      _1806: (x0,x1) => x0.forEach(x1),
      _1807: x0 => x0.getReader(),
      _1808: x0 => x0.cancel(),
      _1809: x0 => x0.read(),
      _1810: x0 => new BroadcastChannel(x0),
      _1811: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1811(f,arguments.length,x0) }),
      _1812: (x0,x1) => x0.postMessage(x1),
      _1813: x0 => x0.close(),
      _1814: (x0,x1,x2,x3) => ({method: x0,headers: x1,body: x2,credentials: x3}),
      _1815: (x0,x1,x2) => x0.fetch(x1,x2),
      _1816: (x0,x1) => x0.key(x1),
      _1817: x0 => x0.trustedTypes,
      _1818: (x0,x1) => { x0.text = x1 },
      _1819: o => o instanceof Array,
      _1820: (a, i) => a.push(i),
      _1823: (a, l) => a.length = l,
      _1824: a => a.pop(),
      _1825: (a, i) => a.splice(i, 1),
      _1826: (a, s) => a.join(s),
      _1827: (a, s, e) => a.slice(s, e),
      _1829: (a, b) => a == b ? 0 : (a > b ? 1 : -1),
      _1830: a => a.length,
      _1831: (a, l) => a.length = l,
      _1832: (a, i) => a[i],
      _1833: (a, i, v) => a[i] = v,
      _1835: o => {
        if (o instanceof ArrayBuffer) return 0;
        if (globalThis.SharedArrayBuffer !== undefined &&
            o instanceof SharedArrayBuffer) {
          return 1;
        }
        return 2;
      },
      _1836: (o, offsetInBytes, lengthInBytes) => {
        var dst = new ArrayBuffer(lengthInBytes);
        new Uint8Array(dst).set(new Uint8Array(o, offsetInBytes, lengthInBytes));
        return new DataView(dst);
      },
      _1838: o => o instanceof Uint8Array,
      _1839: (o, start, length) => new Uint8Array(o.buffer, o.byteOffset + start, length),
      _1840: o => o instanceof Int8Array,
      _1841: (o, start, length) => new Int8Array(o.buffer, o.byteOffset + start, length),
      _1842: o => o instanceof Uint8ClampedArray,
      _1843: (o, start, length) => new Uint8ClampedArray(o.buffer, o.byteOffset + start, length),
      _1844: o => o instanceof Uint16Array,
      _1845: (o, start, length) => new Uint16Array(o.buffer, o.byteOffset + start, length),
      _1846: o => o instanceof Int16Array,
      _1847: (o, start, length) => new Int16Array(o.buffer, o.byteOffset + start, length),
      _1848: o => o instanceof Uint32Array,
      _1849: (o, start, length) => new Uint32Array(o.buffer, o.byteOffset + start, length),
      _1850: o => o instanceof Int32Array,
      _1851: (o, start, length) => new Int32Array(o.buffer, o.byteOffset + start, length),
      _1853: (o, start, length) => new BigInt64Array(o.buffer, o.byteOffset + start, length),
      _1854: o => o instanceof Float32Array,
      _1855: (o, start, length) => new Float32Array(o.buffer, o.byteOffset + start, length),
      _1856: o => o instanceof Float64Array,
      _1857: (o, start, length) => new Float64Array(o.buffer, o.byteOffset + start, length),
      _1858: (t, s) => t.set(s),
      _1859: l => new DataView(new ArrayBuffer(l)),
      _1860: (o) => new DataView(o.buffer, o.byteOffset, o.byteLength),
      _1862: o => o.buffer,
      _1863: o => o.byteOffset,
      _1864: Function.prototype.call.bind(Object.getOwnPropertyDescriptor(DataView.prototype, 'byteLength').get),
      _1865: (b, o) => new DataView(b, o),
      _1866: (b, o, l) => new DataView(b, o, l),
      _1867: Function.prototype.call.bind(DataView.prototype.getUint8),
      _1868: Function.prototype.call.bind(DataView.prototype.setUint8),
      _1869: Function.prototype.call.bind(DataView.prototype.getInt8),
      _1870: Function.prototype.call.bind(DataView.prototype.setInt8),
      _1871: Function.prototype.call.bind(DataView.prototype.getUint16),
      _1872: Function.prototype.call.bind(DataView.prototype.setUint16),
      _1873: Function.prototype.call.bind(DataView.prototype.getInt16),
      _1874: Function.prototype.call.bind(DataView.prototype.setInt16),
      _1875: Function.prototype.call.bind(DataView.prototype.getUint32),
      _1876: Function.prototype.call.bind(DataView.prototype.setUint32),
      _1877: Function.prototype.call.bind(DataView.prototype.getInt32),
      _1878: Function.prototype.call.bind(DataView.prototype.setInt32),
      _1881: Function.prototype.call.bind(DataView.prototype.getBigInt64),
      _1882: Function.prototype.call.bind(DataView.prototype.setBigInt64),
      _1883: Function.prototype.call.bind(DataView.prototype.getFloat32),
      _1884: Function.prototype.call.bind(DataView.prototype.setFloat32),
      _1885: Function.prototype.call.bind(DataView.prototype.getFloat64),
      _1886: Function.prototype.call.bind(DataView.prototype.setFloat64),
      _1887: Function.prototype.call.bind(Number.prototype.toString),
      _1888: Function.prototype.call.bind(BigInt.prototype.toString),
      _1889: Function.prototype.call.bind(Number.prototype.toString),
      _1890: (d, digits) => d.toFixed(digits),
      _1912: () => globalThis.document,
      _1918: (x0,x1) => { x0.height = x1 },
      _1920: (x0,x1) => { x0.width = x1 },
      _1922: (x0,x1) => { x0.pointerEvents = x1 },
      _1931: x0 => x0.style,
      _1934: x0 => x0.src,
      _1935: (x0,x1) => { x0.src = x1 },
      _1936: x0 => x0.naturalWidth,
      _1937: x0 => x0.naturalHeight,
      _1953: x0 => x0.status,
      _1954: (x0,x1) => { x0.responseType = x1 },
      _1956: x0 => x0.response,
      _2082: x0 => x0.style,
      _2559: (x0,x1) => { x0.src = x1 },
      _2689: (x0,x1) => { x0.srcObject = x1 },
      _2713: (x0,x1) => { x0.autoplay = x1 },
      _3318: (x0,x1) => { x0.type = x1 },
      _3326: (x0,x1) => { x0.crossOrigin = x1 },
      _3328: (x0,x1) => { x0.text = x1 },
      _3784: () => globalThis.window,
      _3824: x0 => x0.location,
      _3843: x0 => x0.navigator,
      _4105: x0 => x0.trustedTypes,
      _4106: x0 => x0.sessionStorage,
      _4107: x0 => x0.localStorage,
      _4115: x0 => x0.href,
      _4211: x0 => x0.geolocation,
      _4214: x0 => x0.mediaDevices,
      _4216: x0 => x0.permissions,
      _4217: x0 => x0.maxTouchPoints,
      _4224: x0 => x0.appCodeName,
      _4225: x0 => x0.appName,
      _4226: x0 => x0.appVersion,
      _4227: x0 => x0.platform,
      _4228: x0 => x0.product,
      _4229: x0 => x0.productSub,
      _4230: x0 => x0.userAgent,
      _4231: x0 => x0.vendor,
      _4232: x0 => x0.vendorSub,
      _4234: x0 => x0.language,
      _4235: x0 => x0.languages,
      _4236: x0 => x0.onLine,
      _4241: x0 => x0.hardwareConcurrency,
      _4280: x0 => x0.data,
      _4327: (x0,x1) => { x0.onmessage = x1 },
      _4433: x0 => x0.length,
      _4650: x0 => x0.readyState,
      _4663: (x0,x1) => { x0.binaryType = x1 },
      _4666: x0 => x0.code,
      _4667: x0 => x0.reason,
      _4713: x0 => x0.localDescription,
      _4716: x0 => x0.remoteDescription,
      _4719: x0 => x0.signalingState,
      _4720: x0 => x0.iceGatheringState,
      _4721: x0 => x0.iceConnectionState,
      _4722: x0 => x0.connectionState,
      _4735: (x0,x1) => { x0.onicegatheringstatechange = x1 },
      _4747: x0 => x0.type,
      _4748: x0 => x0.sdp,
      _4749: x0 => x0.type,
      _4751: x0 => x0.sdp,
      _4759: x0 => x0.candidate,
      _4760: x0 => x0.sdpMid,
      _4761: x0 => x0.sdpMLineIndex,
      _4783: x0 => x0.candidate,
      _4819: x0 => x0.track,
      _4825: x0 => x0.headerExtensions,
      _4827: x0 => x0.rtcp,
      _4835: (x0,x1) => { x0.encodings = x1 },
      _4843: x0 => x0.active,
      _4858: x0 => x0.cname,
      _4860: x0 => x0.reducedSize,
      _4872: x0 => x0.clockRate,
      _4879: x0 => x0.payloadType,
      _4882: x0 => x0.codecs,
      _4884: x0 => x0.headerExtensions,
      _4909: x0 => x0.sender,
      _4952: x0 => x0.receiver,
      _4953: x0 => x0.track,
      _4954: x0 => x0.streams,
      _4955: x0 => x0.transceiver,
      _4971: x0 => x0.label,
      _4977: x0 => x0.id,
      _4979: x0 => x0.bufferedAmount,
      _4980: x0 => x0.bufferedAmountLowThreshold,
      _4981: (x0,x1) => { x0.bufferedAmountLowThreshold = x1 },
      _4983: (x0,x1) => { x0.onopen = x1 },
      _4985: (x0,x1) => { x0.onbufferedamountlow = x1 },
      _4991: (x0,x1) => { x0.onclose = x1 },
      _4993: (x0,x1) => { x0.onmessage = x1 },
      _5000: (x0,x1) => { x0.maxPacketLifeTime = x1 },
      _5002: (x0,x1) => { x0.maxRetransmits = x1 },
      _5012: x0 => x0.channel,
      _6344: x0 => x0.signal,
      _6415: () => globalThis.document,
      _6496: x0 => x0.body,
      _6498: x0 => x0.head,
      _6827: x0 => x0.id,
      _6828: (x0,x1) => { x0.id = x1 },
      _8174: x0 => x0.value,
      _8176: x0 => x0.done,
      _8594: () => globalThis.Notification.permission,
      _8868: x0 => x0.url,
      _8870: x0 => x0.status,
      _8872: x0 => x0.statusText,
      _8873: x0 => x0.headers,
      _8874: x0 => x0.body,
      _9657: x0 => x0.id,
      _9664: x0 => x0.kind,
      _9665: x0 => x0.id,
      _9666: x0 => x0.label,
      _9667: x0 => x0.enabled,
      _9668: (x0,x1) => { x0.enabled = x1 },
      _9669: x0 => x0.muted,
      _9902: x0 => x0.width,
      _9904: x0 => x0.height,
      _9906: x0 => x0.aspectRatio,
      _9908: x0 => x0.frameRate,
      _9910: x0 => x0.facingMode,
      _9912: x0 => x0.resizeMode,
      _9914: x0 => x0.sampleRate,
      _9916: x0 => x0.sampleSize,
      _9918: x0 => x0.echoCancellation,
      _9920: x0 => x0.autoGainControl,
      _9922: x0 => x0.noiseSuppression,
      _9924: x0 => x0.latency,
      _9926: x0 => x0.channelCount,
      _9928: x0 => x0.deviceId,
      _9930: x0 => x0.groupId,
      _9984: (x0,x1) => { x0.ondevicechange = x1 },
      _9986: x0 => x0.deviceId,
      _9987: x0 => x0.kind,
      _9988: x0 => x0.label,
      _9989: x0 => x0.groupId,
      _10986: (x0,x1) => { x0.border = x1 },
      _11264: (x0,x1) => { x0.display = x1 },
      _11428: (x0,x1) => { x0.height = x1 },
      _12118: (x0,x1) => { x0.width = x1 },
      _12486: x0 => x0.name,
      _13202: () => globalThis.console,
      _13230: () => globalThis.speechSynthesis,
      _13231: (x0,x1) => { x0.lang = x1 },
      _13233: (x0,x1) => { x0.pitch = x1 },
      _13236: (x0,x1) => { x0.rate = x1 },
      _13238: (x0,x1) => { x0.text = x1 },
      _13239: (x0,x1) => { x0.voice = x1 },
      _13240: x0 => x0.voice,
      _13242: (x0,x1) => { x0.volume = x1 },
      _13243: (x0,x1) => { x0.onstart = x1 },
      _13244: (x0,x1) => { x0.onend = x1 },
      _13245: (x0,x1) => { x0.onpause = x1 },
      _13246: (x0,x1) => { x0.onresume = x1 },
      _13247: (x0,x1) => { x0.onerror = x1 },
      _13248: (x0,x1) => { x0.onboundary = x1 },
      _13250: x0 => x0.lang,
      _13251: x0 => x0.localService,
      _13252: x0 => x0.name,
      _13253: x0 => x0.name,
      _13254: x0 => x0.message,
      _13255: x0 => x0.code,

    };

    const baseImports = {
      dart2wasm: dart2wasm,
      Math: Math,
      Date: Date,
      Object: Object,
      Array: Array,
      Reflect: Reflect,
      WebAssembly: {
        JSTag: WebAssembly.JSTag,
      },
      "": new Proxy({}, { get(_, prop) { return prop; } }),

    };

    const jsStringPolyfill = {
      "charCodeAt": (s, i) => s.charCodeAt(i),
      "compare": (s1, s2) => {
        if (s1 < s2) return -1;
        if (s1 > s2) return 1;
        return 0;
      },
      "concat": (s1, s2) => s1 + s2,
      "equals": (s1, s2) => s1 === s2,
      "fromCharCode": (i) => String.fromCharCode(i),
      "length": (s) => s.length,
      "substring": (s, a, b) => s.substring(a, b),
      "fromCharCodeArray": (a, start, end) => {
        if (end <= start) return '';

        const read = dartInstance.exports.$wasmI16ArrayGet;
        let result = '';
        let index = start;
        const chunkLength = Math.min(end - index, 500);
        let array = new Array(chunkLength);
        while (index < end) {
          const newChunkLength = Math.min(end - index, 500);
          for (let i = 0; i < newChunkLength; i++) {
            array[i] = read(a, index++);
          }
          if (newChunkLength < chunkLength) {
            array = array.slice(0, newChunkLength);
          }
          result += String.fromCharCode(...array);
        }
        return result;
      },
      "intoCharCodeArray": (s, a, start) => {
        if (s === '') return 0;

        const write = dartInstance.exports.$wasmI16ArraySet;
        for (var i = 0; i < s.length; ++i) {
          write(a, start++, s.charCodeAt(i));
        }
        return s.length;
      },
      "test": (s) => typeof s == "string",
    };


    

    dartInstance = await WebAssembly.instantiate(this.module, {
      ...baseImports,
      ...additionalImports,
      
      "wasm:js-string": jsStringPolyfill,
    });
    dartInstance.exports.$setThisModule(dartInstance);

    return new InstantiatedApp(this, dartInstance);
  }
}

class InstantiatedApp {
  constructor(compiledApp, instantiatedModule) {
    this.compiledApp = compiledApp;
    this.instantiatedModule = instantiatedModule;
  }

  // Call the main function with the given arguments.
  invokeMain(...args) {
    this.instantiatedModule.exports.$invokeMain(args);
  }
}
