name: sports_app
description: A digital sports media platform MVP.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  app_links: ^7.0.0
  firebase_core: ^4.5.0
  firebase_messaging: ^16.1.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_riverpod: ^3.3.1
  google_fonts: ^6.1.0
  home_widget: ^0.9.0
  intl: ^0.20.2
  live_activities: ^2.4.7
  livekit_client: ^2.6.5
  permission_handler: ^12.0.1
  riverpod_annotation: ^4.0.2
  share_plus: ^12.0.1
  shimmer: ^3.0.0
  supabase_flutter: ^2.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.8
  network_image_mock: ^2.1.1

  http: any
  riverpod_generator: ^4.0.3
flutter:
  uses-material-design: true
  assets:
    - .env
