import 'dart:io';

void main() {
  final file = File('lib/screens/match_detail_screen.dart');
  final lines = file.readAsLinesSync();
  int start = -1;
  int end = -1;
  for (int i = 0; i < lines.length; i++) {
    if (lines[i].contains('Widget _buildPremiumCreateBanner() {')) {
      start = i;
    }
    if (start != -1 && i > start && lines[i].contains('Widget _buildBentoRoomCard(')) {
      end = i - 1;
      break;
    }
  }
  if (start != -1 && end != -1) {
    lines.replaceRange(start, end, [
      '  Widget _buildPremiumCreateBanner() {',
      '    return GestureDetector(',
      '      onTap: _showCreateMatchRoomDialog,',
      '      child: Container(',
      '        decoration: BoxDecoration(',
      '          borderRadius: BorderRadius.circular(20),',
      '          gradient: const LinearGradient(',
      '            colors: [',
      '               Color(0xFF15151A),',
      '               Color(0xFF22222E),',
      '            ],',
      '            begin: Alignment.topLeft,',
      '            end: Alignment.bottomRight,',
      '          ),',
      '          border: Border.all(color: Colors.white.withValues(alpha: 0.08), width: 1),',
      '          boxShadow: [',
      '            BoxShadow(',
      '              color: Colors.black.withValues(alpha: 0.2),',
      '              blurRadius: 20,',
      '              offset: const Offset(0, 8),',
      '            )',
      '          ],',
      '        ),',
      '        child: ClipRRect(',
      '          borderRadius: BorderRadius.circular(20),',
      '          child: Stack(',
      '            children: [',
      '              Positioned(',
      '                right: -40,',
      '                top: -40,',
      '                child: Container(',
      '                  width: 140,',
      '                  height: 140,',
      '                  decoration: BoxDecoration(',
      '                    shape: BoxShape.circle,',
      '                    boxShadow: [',
      '                      BoxShadow(',
      '                        color: const Color(0xFF8A2BE2).withValues(alpha: 0.4),',
      '                        blurRadius: 50,',
      '                        spreadRadius: 20,',
      '                      )',
      '                    ],',
      '                  ),',
      '                ),',
      '              ),',
      '              Padding(',
      '                padding: const EdgeInsets.symmetric(horizontal: 20.0, vertical: 18.0),',
      '                child: Row(',
      '                  children: [',
      '                    Container(',
      '                      padding: const EdgeInsets.all(12),',
      '                      decoration: BoxDecoration(',
      '                        gradient: const LinearGradient(',
      '                          colors: [Color(0xFF8A2BE2), Color(0xFF4A00E0)],',
      '                          begin: Alignment.topLeft,',
      '                          end: Alignment.bottomRight,',
      '                        ),',
      '                        shape: BoxShape.circle,',
      '                        boxShadow: [',
      '                          BoxShadow(',
      '                            color: const Color(0xFF8A2BE2).withValues(alpha: 0.5),',
      '                            blurRadius: 12,',
      '                            offset: const Offset(0, 4),',
      '                          )',
      '                        ],',
      '                      ),',
      '                      child: const Icon(Icons.mic_rounded, color: Colors.white, size: 26),',
      '                    ),',
      '                    const SizedBox(width: 16),',
      '                    Expanded(',
      '                      child: Column(',
      '                        crossAxisAlignment: CrossAxisAlignment.start,',
      '                        children: [',
      '                          const Text(',
      '                            "Canlı Oda Başlat",',
      '                            style: TextStyle(',
      '                              color: Colors.white,',
      '                              fontSize: 16,',
      '                              fontWeight: FontWeight.w800,',
      '                              letterSpacing: -0.2,',
      '                            ),',
      '                          ),',
      '                          const SizedBox(height: 4),',
      '                          Text(',
      '                            "Taraftarlarla sesli etkileşime geç",',
      '                            style: TextStyle(',
      '                              color: Colors.white70,',
      '                              fontSize: 12,',
      '                              fontWeight: FontWeight.w500,',
      '                            ),',
      '                          ),',
      '                        ],',
      '                      ),',
      '                    ),',
      '                    const SizedBox(width: 8),',
      '                    Container(',
      '                      padding: const EdgeInsets.all(8),',
      '                      decoration: BoxDecoration(',
      '                        color: Colors.white.withValues(alpha: 0.1),',
      '                        shape: BoxShape.circle,',
      '                      ),',
      '                      child: const Icon(Icons.add, color: Colors.white, size: 20),',
      '                    ),',
      '                  ],',
      '                ),',
      '              ),',
      '            ],',
      '          ),',
      '        ),',
      '      ),',
      '    );',
      '  }',
    ]);
    file.writeAsStringSync(lines.join('\\n'));
    print('Replaced successfully!');
  } else {
    print('Failed to find bounds. start: \$start, end: \$end');
  }
}
